r-lib/rlang

- R/arg.R
- R/call.R
- R/dots.R
- R/pairlist.R
- man/arg_info.Rd
- man/call_standardise.Rd
- tests/testthat/test-arg.R
- tests/testthat/test-call.R
- tests/testthat/test-dots.R
This adds a `name` field to `arg_info()`'s output. It reports the name of the original formal argument. This is used in the lazyeval compatibility layer because `lazy()` returns the formal name when the argument is missing (whereas `arg_info()` and `arg_expr()` return the missing arg for consistency).
To make this possible `call_standardise()` gains a `add_missings()` argument so that `f()` is expanded to `f(x = )`. I wonder if `add_missings` and `enum_dots` should be gathered in a single bool argument `full`?
> Fix formal name

- R/tidy-capture.R
- R/tidy-eval.R
- src/unquote.c
- tests/testthat/test-tidy-capture.R
- tests/testthat/test-tidy-eval.R
- tests/testthat/test-tidy-unquote.R
* This guards formulas on capture so we are compatible with purrr's lambdas cc @jennybc.
* This streamlines capture of literals so they are not rewrapped in a quosure. This should make it easier for instance to pass default `NULL` arguments between multiple NSE functions and check for a `NULL` quosure.
> Fix formula self eval

- DESCRIPTION
- R/compat-oldrel.R
- R/dots.R
- R/quo-enquo.R
- src/capture.c
- tests/testthat/test-dots.R
- tests/testthat/test-tidy-capture.R
This fixes some revdep failures in dplyr due to forced dots being passed to `bind_rows()`. E.g. in this situation:
```r
lapply(x, bind_rows)
```
Forced dots are returned as is when passed by value, and keep issuing an error if passed by expression.
> Fix forced dots

- R/dots.R
- R/quos.R
- man/dots_list.Rd
- man/dots_values.Rd
- tests/testthat/test-dots.R
So all functions taking dots by value now trim trailing empty arguments by default. E.g.
```r
chr("a", )
#> [1] "a"
```
> Add `.ignore_empty` arg to dots_list() and dots_splice()

- R/fn.R
- tests/testthat/test-fn.R
Closes #75 
Closurised operators have now arguments `.x`, `.y` etc like lambdas created with formulas. This should make it easier to pass arguments, e.g. 
```r
map_int(1:3, `-`, .x = 10)
#> [1] 9 8 7
map_int(1:3, `-` .y = 10)
#> [1] -9 -8 -7
```
> Support most primitive operators in as_closure()

- vignettes/tidy-evaluation.Rmd
Congratulations for the release!
I found a weird index name for the vignette "Tidy evaluation". (Maybe is this a mistake when you copied from another existing vignette?)
> Vignettes: 	Specifying fonts
https://cran.r-project.org/web/packages/rlang/index.html
> Fix a wrong vignette index

- src/capture.c
- tests/testthat/test-quo-enquo.R
This fixes the "Argument was already evaluated" error of the lisy and epidata packages.
This one is kind of serious. Should we make another rlang release before dplyr's?
cc @krlmlr
> Fix capture of optimised promises

- R/stack.R
- man/stack.Rd
Markdown gotcha: a ” 1.” ending of a sentence happened to start a `#'`-line.
> Eliminate spurious enumeration in stack doc

- NEWS.md
- R/quo.R
~~lncludes a review of the call stack UI as I got confused by a simple `call_depth()` (even though I ended up using `sys.parent()` to make the top-level check).~~ This is now in #197
> enquo() as alias to quo() when called at top-level

- NEWS.md
- R/cnd.R
- R/eval-tidy.R
- src/cnd.c
- tests/testthat/test-conditions.R
- `eval_tidy()` does not map over lists anymore.
- `cnd_signal()` accepts character vectors of S3 classes and returns `NULL` invisibly.
> Fix couple of bugs before release

- NEWS.md
- src/env.c
- src/env.h
- src/eval-tidy.c
- tests/testthat/test-tidy-eval.R
The `.env` pronoun should refer to the current quosure env. Closes #174.
> Fix .env pronoun

- src/Makevars
This forces 'rlang.c' to be recompiled if any of it's dependencies are out
of date.
Rather than requiring pkgbuild modifications an easier solution might be to use a Makevars which handles the dependency resolution.
Taking this idea further could have `rlang.c` written based on the `files` variable in the Makevars, which would remove the redundant filenames. You could also populate `files` with wildcards so they wouldn't have to be listed explicitly, but this requires GNU make extensions.
Fixes https://github.com/r-lib/pkgload/issues/50, https://github.com/r-lib/pkgbuild/pull/13
> Add a Makevars file for unity builds

- R/types.R
- man/is_integerish.Rd
- tests/testthat/test-types.R
Previously, `is_integerish(x, n)` would disregard `n` for `x` an integer vector.
> Ensure that is_integerish() heeds length requirement

- R/types.R
- tests/testthat/test-types.R
Minor edit of `is_*(x) && length(x) == 1` to `is_*(x, n = 1)`, in bodies of scalar predicates.
> Simplification of scalar predicates

- R/parse.R
It seems that the valid suffix is `_quosure` or `_quosures`.
> Is there still a version prefixed or sufixed with `f_` or `_f`?

- R/quo.R
- man/quosure.Rd
> fix typos in the man page of `quosure`: absence of space

- R/types.R
- man/is_integerish.Rd
- man/type-predicates.Rd
- tests/testthat/test-types.R
- `is_integerish(c(Inf, -Inf, NaN))` now returns `TRUE`
- There is a new `finite` argument for `is_integerish()` and `is_double()` to check whether all values are finite.
> Better handling of non-finite values in numeric predicates

- NEWS.md
- R/dots.R
- R/expr.R
- R/quo.R
- R/quos.R
- R/vec-new.R
- man/dots_list.Rd
- man/dots_values.Rd
- man/expr.Rd
- man/quosure.Rd
- man/quosures.Rd
- src/arg.c
- src/dots.c
- src/expr-interp.c
- src/expr-interp.h
- src/init.c
- src/rlang/rlang.h
- src/rlang/vec-chr.h
- tests/testthat/helper-capture.R
- tests/testthat/test-tidy-unquote.R
Includes #297, closes #279.
To treat `expr(list(a := foo))` as synonym of `expr(list(a = foo))` and allow name-unquoting everywhere.
I'm not too fond of the `unquote_names` argument name, but I can't think of anything better.
> Deep unquoting of names

- tests/testthat/test-dots.R
@lionel- please let us know if this is expected.
Related to https://github.com/rstudio/sparklyr/issues/1159
> Add unit test to ensure dots_splice() doesn't squash S3 objects

- R/parse.R
If a colon is used  to separate expressions as the documentation currently states parse_exprs and parse_quosures will return a single expression/quosure, not multiple
> separate expressions by semicolons, not colons

- R/eval-tidy.R
- man/eval_tidy.Rd
I added a little documentation to capture @lionel-'s comments from https://github.com/tidyverse/dplyr/issues/3286. Feel free to merge if this is helpful, not worries if it's not.
I added a few examples that use magrittr pipes (`%>%`), but `\dontrun{}`-ed run them to avoid making magrittr a dependency.
> Add documentation of `.env` vs. unquoting

- R/lifecycle-retired.R
- tests/testthat/test-retired.R
Will be refactoring to `node_cdr()` on our end but figured this is worth fixing in case it breaks stuff in the wild.
cc @lionel- this is the issue I mentioned
Closes https://github.com/rstudio/sparklyr/issues/1221
> fix typo in lang_head() and lang_tail()

- NEWS.md
- R/attr.R
- R/lifecycle-retired.R
- R/vec-new.R
- man/new-vector-along.Rd
- man/new-vector.Rd
- tests/testthat/test-vec-new.R
Includes #403 
For the `_along` family it defaults to the names of the input vector which should be useful when pre-allocating output with `new_list_along()` etc.
> Add `names` argument to vector constructors

- NEWS.md
- R/cnd-handlers.R
- man/with_handlers.Rd
- tests/testthat/test-cnd.R
So `with_handlers(expr, error = identity)` is equivalent to `tryCatch(expr, error = identity)`.
Closes #499
> Treat bare functions as exiting handlers

- R/calltrace.R
- tests/testthat/calltrace-print.txt
- tests/testthat/test-calltrace.R
With this fix the srcrefs are grabbed from the sys.calls. This way the srcrefs reference the location of the call rather than the location of the definition of the function being called.
I toyed with using the srcrefs to print the calls themselves, which would allow us to get more accurate calls in case primitive functions are involved (we could observe `x <- i()` instead of just `i()`). However I found some issues when function bodies are not wrapped in `{`. I took note of this problem in my backlog of R core issues to fix.
I find there's something odd about `calltrace()`. I feel it lacks an underscore, however I don't want to use `call_` as a prefix here. How about `backtrace()` or `trace_back()`?
> Fix calltrace

- .gitignore
- appveyor.yml
- configure
- configure.win
- src/lib/cnd.c
- src/lib/rlang.h
- tests/testthat/calltrace-print.txt
- tests/testthat/test-calltrace.R
cc @mvkorpel
@kevinushey Is this a portable and safe way of simulating interrupts on Windows environments? Cf `r_interrupt()` in cnd.c.
> Fix build and simulated interrupts on Windows

- NEWS.md
- R/env-binding.R
- R/env.R
- R/types.R
- src/export/init.c
- src/internal/env-binding.c
- tests/testthat/test-env-binding.R
- tests/testthat/test-env.R
So that symbols are printed as `<sym>` and missing arguments as `<missing>`.
```r
env <- env(
x = missing_arg(),
y = quote(foo)
)
env_print(env)
#> <environment: 0x7fbf9972ecc8>
#>   parent: <environment: global>
#>   bindings:
#>    * x: <missing>
#>    * y: <sym>
```
> Handle symbols in type_sum and env_print()

- NEWS.md
- R/env.R
- man/env_print.Rd
- tests/testthat/test-env.R
To make interactive exploration easier
Fixes #567
> Use get_env() in env_print()

- R/deparse.R
The increase_indent() function was actually creating an invalid
object via the expression `new_node(FALSE, 0L)`.
The `new_node` function is a wrapper for the `cons()` function, which
expects two arguments:
* car: the value of the node to be created
* tail (or cdr): a pairlist (or NULL) which continues the list after the  new node created
The expression `new_node(FALSE, 0L)` then actually passes an integer vector
as the cdr or tail instead of a pairlist, creating an illegal object.
You can verify this by evaluating the following expressions:
x <- new_node(FALSE, 0L)
length(x[[1]])
Which will crash your R session.
The code does work at the moment because GNU R does not actually check
that the cdr argument to the cons() function is valid, and the value is
only accessed via the CDR macros, …
> Fix handling of indent_status in deparse()

- NEWS.md
- R/cnd.R
- R/lifecycle.R
- R/quasiquotation.R
- man/lifecycle.Rd
- man/quasiquotation.Rd
- src/export/exported-tests.c
- src/export/init.c
- src/internal/expr-interp.c
- src/lib/cnd.c
- src/lib/cnd.h
- tests/testthat/test-c-api.R
- tests/testthat/test-quasiquotation.R
@hadley How about giving examples in the warning?
```r
expr(rlang::UQ("foo"))
#> [1] "foo"
#> Warning message:
#> Prefixing `UQ()` with the rlang namespace is deprecated as of rlang 0.3.0.
#> Please use the non-prefixed form or `!!` instead.
#>
#>   # Bad:
#>   rlang::expr(mean(rlang::UQ(var) * 100))
#>
#>   # Ok:
#>   rlang::expr(mean(UQ(var) * 100))
#>
#>   # Good:
#>   rlang::expr(mean(!!var * 100))
```
> Lifecycle of UQE() and namespaced UQ()/UQS() calls

- R/cnd.R
- R/eval-tidy.R
- R/lifecycle-retired.R
- R/lifecycle.R
- R/utils.R
- man/as_data_mask.Rd
- man/as_overscope.Rd
- man/eval_tidy.Rd
- man/eval_tidy_.Rd
- man/lifecycle.Rd
- src/export/exported-tests.c
- src/export/exported.c
- src/export/init.c
- src/internal/eval-tidy.c
- src/internal/expr-interp.c
- tests/testthat/test-c-api.R
- tests/testthat/test-eval-tidy.R
- tests/testthat/test-retired.R
* Deprecate bare environments passed to `eval_tidy()` and `as_data_mask()` Passing bare environments is confusing because their parents is silently changed to the current evaluation env. (There is a similar confusion in `base::eval()` except that it goes the other way around, the current evaluation env is silently ignored.)
* Deprecate `parent` arguments of `as_data_mask()` and `new_data_mask()`.
The idea behind these two changes is that the parent of the data mask is undetermined at time of creation. The parent changes during evaluation to the `env` argument of `eval_tidy()`, or to quosure environments when applicable. Given these semantics, allowing parents at data mask creation and supporting bare environments were confusing.
Closes #571
> Update data mask API

- R/expr.R
- tests/testthat/test-quo.R
When the expression is a bare symbol, rather use as_string and its magic handling of encoding. closes #611
Same fix as https://github.com/tidyverse/dplyr/pull/3830 but potentially benefitting outside of dplyr.
> Gracefully handle expr_text(<symbol>).

- R/deparse.R
- tests/testthat/test-deparse.R
Fixes #581 by adding a check to `call_deparse()` to see if the expression in the CAR slot of the call should be wrapped in parentheses for printing.
I picked the expressions that should have parentheses using the switch statement from `op_deparse()` and eyeballing which ops should have parentheses and which not.
> Add parentheses to call CAR when printing if required (#581)

- R/env-binding.R
- src/Makevars
- src/export/init.c
- src/internal/env-binding.c
- src/lib.c
- src/lib/env-binding.c
- src/lib/env-binding.h
- src/lib/env.c
- src/lib/env.h
- src/lib/rlang.h
- src/lib/sexp.h
- src/lib/vec-chr.c
- src/lib/vec-chr.h
- src/lib/vec.h
- tests/testthat/test-env-binding.R
- tests/testthat/test-env.R
To preserve copy semantics and avoid bypassing documented API.
Can't prevent forcing promises for now.
Closes #621
> Rewrite r_env_clone()

- NEWS.md
- R/dots.R
- R/vec-new.R
- man/dots_values.Rd
- man/splice.Rd
- man/tidy-dots.Rd
- src/export/init.c
- src/internal/dots.c
- tests/testthat/test-dots.R
Allow dots collectors to preserve empty arguments.
> Add `.forward_empty` argument to dots collectors

- NEWS.md
- R/env-binding.R
- R/env.R
- R/vec-new.R
- man/env_bind.Rd
- tests/testthat/test-env-binding.R
Includes #619 for empty argument support.
- Allow removing bindings by supplying empty arguments:
```
env_bind(env, foo = )
```
- Return old binding values from `env_bind()`. When there is no old value, missing arguments are returned.
The combination of these features ensures the following roundtrip always restores the environment state:
```
old <- env_bind(env, ...)
env_bind(env, !!!old)
```
> Return old values from `env_bind()`

- NEWS.md
- R/dots.R
- R/fn.R
- R/quasiquotation.R
- man/fn_body.Rd
- man/quasiquotation.Rd
- man/splice.Rd
- man/tidy-dots.Rd
- src/internal/dots.c
- src/internal/expr-interp.c
- src/internal/internal.c
- src/internal/internal.h
- src/lib/env.c
- src/lib/env.h
- tests/testthat/helper-cnd.R
- tests/testthat/test-dots.R
- tests/testthat/test-fn.R
- tests/testthat/test-quasiquotation.R
Closes #572
Changes for `list2()`:
* Accept pairlists
* Fail with language objects
* Call `base::as.list()` for classed vector objects
Changes for `exprs()` and `quos()`:
* Non-vector non-language objects like environments and functions now fail. Before they were automatically wrapped in a list to allow splicing.
* Call `base::as.list()` for classed vector objects.
* Soft-deprecate splicing of language objects, including scalar quosures. This makes this kind of code throw an error: https://github.com/tidyverse/tidyr/commit/82ef03af587b5ad57e6edf185a0ca5af8c969d4b#diff-65e6a5a29a28bb3768b7a3c192f952f1R147.
```r
#> Warning message:
#> Unquoting language objects with `!!!` is soft-deprecated as of rlang 0.3.0.
#> Please use `!!` instead.
#>
#>   # Bad:
#>   dplyr::select(data, !!!enquo(x)) …
```
> Fix !!! input types

- NEWS.md
- R/eval-tidy.R
- R/expr.R
- R/lifecycle.R
- R/quotation.R
- R/sym.R
- man/dots_definitions.Rd
- man/exprs_auto_name.Rd
- man/lifecycle.Rd
- man/quotation.Rd
- src/internal/dots.c
- tests/testthat/test-deparse.R
- tests/testthat/test-eval-tidy.R
- tests/testthat/test-expr.R
- tests/testthat/test-quotation.R
Includes #637.
- Use `quo_name()` instead of `quo_text()` to auto name quoted expressions as multi-line text does not make sense for names.
- Use `pillar::type_sum()` in `quo_name()`. Motivation for this change is given in #573.
- Handle `.data` pronouns in `quo_name()`. This way `group_by(df, name)` and `group_by(df, .data$name)` receive the same default name.
Closes #573.
Closes #468.
> Use quo_name() to create default names

- NEWS.md
- R/compat-purrr.R
- R/dots.R
- R/quotation.R
- R/vec-new.R
- man/dots_values.Rd
- man/quotation.Rd
- man/splice.Rd
- man/tidy-dots.Rd
- src/export/exported-tests.c
- src/export/init.c
- src/internal/dots.c
- src/lib/vec-chr.c
- src/lib/vec-chr.h
- src/lib/vec-lgl.c
- src/lib/vec-lgl.h
- tests/testthat/helper-c-api.R
- tests/testthat/test-c-api.R
- tests/testthat/test-compat.R
- tests/testthat/test-dots.R
```r
mylist <- function(...) {
dots_list(..., .homonyms = "first")
}
mylist(1, a = 2, b = 3, 4, b = 5, b = 6, 7, a = 8)
#> [[1]]
#> [1] 1
#>
#> $a
#> [1] 2
#>
#> $b
#> [1] 3
#>
#> [[4]]
#> [1] 4
#>
#> [[5]]
#> [1] 7
```
```r
mylist <- function(...) {
dots_list(..., .homonyms = "last")
}
mylist(1, a = 2, b = 3, 4, b = 5, b = 6, 7, a = 8)
#> [[1]]
#> [1] 1
#>
#> [[2]]
#> [1] 4
#>
#> $b
#> [1] 6
#>
#> [[4]]
#> [1] 7
#>
#> $a
#> [1] 8
```
```r
mylist <- function(...) {
dots_list(..., .homonyms = "error")
}
mylist(1, a = 2, b = 3, 4, b = 5, b = 6, 7, a = 8)
#> Error: Arguments can't have the same name. We found these problems:
#> * Multiple arguments named `a` at positions 2 and 8
#> * Multiple arguments named `b` at positions 3, 5 and 6
mylist(1, a = 2, b = 3, 4, b = 5, b = 6, 7)
#> Error: …
```
> Add .homonyms argument to dots collectors

- NEWS.md
- R/cnd.R
- R/lifecycle.R
- man/abort.Rd
- man/cnd.Rd
- man/lifecycle.Rd
- src/export/init.c
- src/lib/cnd.c
- src/lib/cnd.h
- tests/testthat/test-cnd-error-str.txt
- tests/testthat/test-cnd.R
Since it's superseded by backtraces.
Directly deprecated because there are likely very few users of this argument, if any, and it should be harmless to ignore it in most cases.
Closes #520
> Deprecate `call` argument of condition ctors

- NEWS.md
- R/quotation.R
- man/dots_definitions.Rd
- man/quotation.Rd
- tests/testthat/test-quotation.R
With this change, `enquos()` now ignore all missing arguments if ignore_empty is set to "all":
```r
myquotingfn <- function(x, y, ...) {
enquos(x, y, ..., .ignore_empty = "all")
etc.
}
```
This is meant to simplify code like https://github.com/tidyverse/ggplot2/blob/3e1e6e43af82faf59e37df0724b65c8d829c7b07/R/aes.r#L79.
`"trailing"` still only applies to dots. It doesn't seem to make much sense for named arguments.
> Support `.ignore_empty = "all"` in enexprs() and enquos()

- NEWS.md
- R/quo.R
- man/as_quosure.Rd
- man/is_quosureish.Rd
- tests/testthat/test-quo.R
And fail when formula does not contain an environment. This seems safer because if an unevaluated formula turns up it likely means something went wrong earlier.
Closes #433
> Require environment in as_quosure()

- src/Makevars
> Fix `nm.exe` messages at shlib creation on Windows

- R/expr.R
- R/lifecycle.R
- R/quo.R
- man/expr_label.Rd
- man/lifecycle.Rd
- man/quo_label.Rd
* Improve explanation of `quo_name()` and `quo_text()`. Mention they should not be used for programming and point to `as_string()` for symbol to text conversion. I noticed in the revdeps many people use `quo_name()` and even `quo_text()` for converting symbols to strings.
* Put `expr_` deparsers in the questioning stage. Perhaps the `quo_` deparsers should too? I thought not because we still mention them a lot in the tidy eval docs.
> Documentation of expression deparsers

- R/trace.R
- man/trace_back.Rd
- tests/testthat/helper-trace.R
- tests/testthat/test-trace-collapse-eval.txt
- tests/testthat/test-trace-collapse-evalq.txt
- tests/testthat/test-trace-collapsed1.txt
- tests/testthat/test-trace-trim.txt
- tests/testthat/test-trace.R
~Includes #660 to avoid merge conflicts with the namespaced backtraces.~
Closes #491
Closes #521
> Add `trim` argument to trace_back()

- NEWS.md
- R/exec.R
- man/exec.Rd
Small overlook, the argument to `exec()` isn't prefixed with a dot and uses the particle for formulas instead of function. Shouldn't have any consequences on revdeps since that's a new function and only the first argument is renamed.
> Take `.fn` argument in `exec()`

- R/fn.R
This is the purpose of `args()`.
> Get pseudo-formals of primitives with args()

- NEWS.md
- R/arg.R
- man/missing_arg.Rd
Occasionally it's useful to substitute missing values by other values, e.g. explicit `NULL`.
> Add default argument to maybe_missing()

- R/cnd.R
Update function name in warning message
> Typo in `add_backtrace` warning message: `enframe` to `entrace`

- R/fn.R
- man/as_function.Rd
Some recent discussions elsewhere have affirmed my sense that `.x` is better to emphasize in anonymous function, as opposed to `.`. Specifically, in dplyr pipelines, I think it's best if people associate `.` with the primary data frame that is being piped and use `.x` when writing a lambda in scoped verbs.
> Emphasize `.x` (over `.`) in as_function() docs

- NEWS.md
- R/operators.R
- man/op-na-default.Rd
- src/lib/replace-na.c
- tests/testthat/test-operators.R
These changes allow `x %|% y` when `y` is of same length as `x`. For example:
```r
> c(1L, NA, 3L, NA, NA) %|% 0L # usual use case
[1] 1 0 3 0 0
> c(1L, NA, 3L, NA, NA) %|% (6L:10L) # modified use case
[1]  1  7  3  9 10
```
Changes: 
* `R/operators.R`: I modified the documentation of %|% to reflect the changes in behaviour of this function. I also modified the `stopifnot()` checks accordingly.
* `src/lib/replace-na.c`: Rather than looking at the length of `y` in `replace_na_()`, I created a separate function `replace_na_vec_()` and call the correct function depending on the length of `y`, as not to sacrifice speed by having more if/else statements.
* `tests/testthat/test-operators.R`: I added tests to check whether `x %|% y` is working correctly when `length(y) == length(x)`, and also …
> Allow %|% to work when y is of same length as x

- R/fn.R
- man/is_function.Rd
The `is_function()` documentation refers to `fn_fmls()` as a "function that returns a representation of formal arguments for primitive functions", which is no longer true as of rlang v 0.4.0 (but was true for rlang v0.3.1). `fn_fmls()` currently throw an error for primitives. 
From the `fn_fmls()` doc page: 
> Unlike `formals()`, these helpers throw an error with primitive functions instead of returning NULL.
As a side note, I'm a little salty about this loss of functionality. Does `rlang` now not have a way of accessing primitive function arguments?
> changed outdated doc reference to fn_fmls

- _pkgdown.yml
There is a bunch of other functions missing:
Warning: Topics missing from index: are_na, as_label, as_name, as_string, as_utf8_character, caller_fn, catch_cnd, cnd, cnd_muffle, cnd_signal, cnd_type, done, dots_n, dots_values, env_bury, env_lock, has_length, has_name, is_callable, is_condition, is_copyable, is_named, is_reference, is_stack, lang_head, last_error, lifecycle, missing, new-vector-along-retired, new-vector, pairlist2, prim_name, restarting, return_from, rlang_backtrace_on_error, rst_abort, rst_list, string, with_env, with_restarts
For questioning/deprecated functions, do we want a "Retired functions" section, or do we use `@keywords internal`?
> Add entrace to index

- NEWS.md
- R/cnd.R
- R/trace.R
- tests/testthat/test-cnd-error-parent-default.txt
- tests/testthat/test-cnd-error-parent-full.txt
- tests/testthat/test-cnd-error-print-base-parent.txt
- tests/testthat/test-cnd.R
- tests/testthat/test-with-abort.txt
The current display logic of the backtraces is kind of backwards when errors have parents.
Say we have this error which has one parent and one grand-parent:
```r
tidyselect::vars_rename(letters, new = 1.5)
#> Error: Must select with column names or positions.
#> x Lossy cast from `i` <double> to <integer>.
```
The simplified backtrace currently displays as:
```r
last_error()
#> <error/tidyselect_error_index_bad_type>
#> Must select with column names or positions.
#> x Lossy cast from `i` <double> to <integer>.
#> Backtrace:
#>  1. tidyselect::vars_rename(letters, new = 1.5)
#>  2. purrr::map_if(...) /Users/lionel/Dropbox/Projects/R/tidyverse/tidyselect/R/vars-rename.R:12:2
#>  3. purrr::map(.x[!sel], .else, ...)
#>  4. tidyselect:::.f(.x[[i]], ...)
#>  5. tidyselect::as_indices(., .vars) …
```
> Improve display of backtraces of parent errors

- R/rlang.R
A user mentioned a forward compatibility issue between rlang 0.4.0 and dplyr 0.7.8: https://github.com/tidyverse/dplyr/issues/4600.
As I'm about to release rlang 0.4.1, I'd like to experiment with a load-time warning to detect packages known to be forward-incompatible. Loading rlang with an old dplyr would give this warning:
```
Warning message:
As of rlang 0.4.0, dplyr must be at least version 0.8.0.
✖ dplyr 0.7.8 is too old for rlang 0.4.1.
ℹ Please update dplyr with `install.packages("dplyr")`.
```
On Windows platforms, we link to https://github.com/jennybc/what-they-forgot/issues/62 where the second comment provide a rough guide on proper updating of packages.
```
Warning message:
As of rlang 0.4.0, dplyr must be at least version 0.8.0.
✖ dplyr 0.7.8 is too old for rlang 0.4.1.
ℹ …
```
> Warn on load when downstream dep is incompatible

- NEWS.md
- R/cnd-abort.R
- R/cnd-signal.R
- R/cnd.R
- man/abort.Rd
- man/cnd.Rd
- tests/testthat/test-cnd-signal.R
Branched from #865.
Progress towards #862.
Renames `.subclass` to `class` in condition constructors. The old arguments are still fully allowed because this is a patch release.
> Fix `class` parameters

- R/call.R
Removed the final sentence in the description of `is_call` which makes reference to nonexistent functions  `is_unary_call()` and `is_binary_call()`.
> update is_call description

- NEWS.md
- R/arg.R
- R/cnd-error.R
- R/trace.R
- tests/testthat/test-arg.R
This matches the logic of match.arg -- if length of argument is greater than 1, it must be identical to the values argument.
Fixes #874 
A few places in code base need to now call `arg_match` before passing to subsequent functions that have the options list in a different order so as to be robust to this stricter test. If other packages also rely on the less strict behavior, perhaps it would be safer to introduce this as a warning first?
> Make arg_match require single argument if given

- src/internal/eval-tidy.c
- tests/testthat/test-eval-tidy.R
``` r
library(rlang)
e <- env()
env_bind_lazy(e, a = c(1, 2, 3))
msk <- new_data_mask(e)
msk$.data <- as_data_pronoun(msk)
eval_tidy(expr(.data$a * 2), msk)
#> [1] 2 4 6
```
I'll add tests ... if I'm on the right track @lionel-.
> Resolve promise in .data$<x> when <x> is a promise in the mask.

- R/compat-downstream-dep.R
- R/compat-linked-version.R
- R/rlang.R
Branched from #926. Implemented in a standalone compat file that can be copied in zero-dep packages, but will eventually be exported from rlang as well.
Sometimes a package is updated with known breaking changes. Broken downstream dependencies can then be updated to fix the breakage and bump the required version of the upstream package in their DESCRIPTION file. However that doesn't cover the common case of updating the upstream dependencies independently. Since there is no way of specifying minimal versions of downstream dependencies in DESCRIPTION, the downstream packages won't be updated even though they are no longer compatible. This can result in surprising and hard to debug behaviour.
The goal of `check_downstream_deps()` is to reduce friction when breaking updates are released with …
> Add `check_downstream_deps()`

- R/operators.R
- src/lib/replace-na.c
- tests/testthat/helper-output.R
- tests/testthat/test-operators-replace-na.txt
- tests/testthat/test-operators.R
Mainly for speed, but also for better errors
I used `verify_output()`, and have the matching hard error checks as well. You don't have a `verify_errors()` stub yet so I didn't wrap them in that, do you want one?
``` r
library(rlang)
x <- letters
```
```r
bench::mark(1 %|% 1, iterations = 100000)
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 1 %|% 1       5.8µs    7.5µs   128412.    10.9KB     92.5
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 1 %|% 1       321ns    446ns  2096734.    6.48KB     105.
```
```r
bench::mark(letters %|% "", iterations = 100000)
#> # A tibble: 1 x 6
#> …
```
> Replace `stopifnot()` calls with C level checks in `%|%`

- NEWS.md
- R/attr.R
- R/fn.R
- R/formula.R
- R/lifecycle-retired.R
- src/Makevars
- src/export/exported.c
- src/export/init.c
- src/internal.c
- src/internal/attr.c
- src/internal/internal.c
- src/lib/eval.c
- src/lib/eval.h
- src/lib/fn.h
- src/lib/formula.c
- src/lib/formula.h
- src/lib/replace-na.h
- src/lib/rlang.h
- src/lib/sym.c
- src/lib/sym.h
- src/lib/vec-chr.c
- src/lib/vec-chr.h
To do this, I've had to implement a few other things in C:
- `is_function()`
- While I was there, I went ahead and did `is_closure()`, `is_primitive()`, `is_primitive_eager()` and `is_primitive_lazy()` too
- `is_formula()`
- `names2()`
I've created a new file, `internal/attr.c` to house the C implementations of `set_names()` and `names2()`.
For `names2()`, we fall back to the R level `names()` when `x` is an object to allow it to dispatch. We also handle pairlists and language objects specially, like `getAttrib()` does.
For `set_names()`, we always eventually set the names with `names<-()` rather than with `r_poke_names()`. The reason for this is that `do_namesgets()` has the ability to shallow copy _attributes_ using an ALTREP wrapper with `R_shallow_duplicate_attr()`. This isn't exposed …
> Implement `set_names()` in C

- src/internal/attr.c
- tests/testthat/test-attr.R
I forgot we can't use `r_length()` unconditionally to check the length of the names vs the length of `x`. We need to fallback to the R level `length()` if `x` is an object
Found while running vctrs tests. With this PR, tests now pass for vctrs and dplyr with no issues
> Generically check length in `set_names()`

- NEWS.md
- R/dots.R
- src/internal/dots.c
- src/internal/internal.c
- src/internal/internal.h
- tests/testthat/test-node.R
- tests/testthat/test-nse-force.R
Part of tidyverse/dplyr#4931
@lionel- would you like me to call the helper `rlang_as_list()` or `rlang_chop2()`? I felt like the first seemed more appropriate here, but don't have a strong preference.
Before:
``` r
library(rlang)
f <- set_names(factor(c("a", "b")), c("x", "y"))
qs <- quos(!!!f, .named = TRUE)
qs
#> <list_of<quosure>>
#> 
#> $`<fct>`
#> <quosure>
#> expr: ^<fct>
#> env:  empty
#> 
#> $`<fct>`
#> <quosure>
#> expr: ^<fct>
#> env:  empty
lapply(qs, eval_tidy)
#> $`<fct>`
#> x 
#> a 
#> Levels: a b
#> 
#> $`<fct>`
#> y 
#> b 
#> Levels: a b
```
After:
``` r
library(rlang)
f <- set_names(factor(c("a", "b")), c("x", "y"))
qs <- quos(!!!f, .named = TRUE)
qs
#> <list_of<quosure>>
#> 
#> $x
#> <quosure>
#> expr: ^<fct>
#> env:  empty
#> 
#> $y
#> <quosure>
#> expr: ^<fct>
#> env: …
```
> Use `[[` to convert S3 and S4 objects to list in `!!!` 

- R/dots.R
- tests/testthat/test-nse-force.R
I forgot that `[[<-` can shorten a list if you assign `NULL` directly to it. I've given lists their own path to avoid repeatedly checking if each element `is.null()` when splicing an S3 type that isn't a list.
> Special case lists in `rlang_as_list()`

- R/cnd-abort.R
- man/abort.Rd
I think there are places in the docs that suggest `type` --> `.subclass` is the most recent change. But in fact there is also `.subclass` --> `class`. I'm not entirely sure I have the wording right, so feel free to refine this PR or close and make the changes separately. But I am pretty sure this is an improvement.
> Update docs around `class` (vs `.subclass`)

- R/events.R
- tests/testthat/test-env-binding.R
- tests/testthat/test-state.R
Closes #980
Implements `after = ` logic with a custom stack of exit expressions so it works on old R versions.
> Run exit expressions in LIFO order

- NEWS.md
- R/dots.R
- R/nse-defuse.R
- man/dots_definitions.Rd
- man/list2.Rd
- man/nse-defuse.Rd
- src/internal/dots.c
- src/lib/vec-chr.h
- tests/testthat/test-dots.R
Same functionality as with `enquos()`. Closes #957.
```r
dots_list(1, letters, .named = TRUE)
#> $`1`
#> [1] 1
#>
#> $letters
#>  [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s" "t" "u"
#> [22] "v" "w" "x" "y" "z"
```
> Add `.named` argument to `dots_list()`

- NEWS.md
- R/env-binding.R
- man/env_unbind.Rd
- src/export/init.c
- src/internal/env-binding.c
- src/internal/eval-tidy.c
- src/lib/env.c
- src/lib/env.h
- tests/testthat/helper-c-api.R
- tests/testthat/test-c-api.R
- tests/testthat/test-env-binding.R
- tests/testthat/test-env.R
* Move `env_has()` and `env_unbind()` implementations to C.
* Use `R_removeVarFromFrame()` on R 4.0.
* Clean up C API for environments a bit.
> Move `env_has()` and `env_unbind()` to C

- NEWS.md
- R/env-binding.R
- src/export/exported.c
- src/internal/env-binding.c
- src/lib/sym-unescape.c
- src/lib/sym.h
- src/lib/vec-chr.h
Relies on #1005 so we don't use things like `rm()` or `exists()` which will warn.
The workaround implemented in this PR depends on `Rf_translateChar()` not issuing warnings. Hopefully it stays that way.
> Fix encoding warnings on R 4.0

- src/internal/eval-tidy.c
- src/internal/utils.h
- tests/testthat/test-eval-tidy.R
Fix #924 
This ended up a bit complicated as in order to work correctly we have to search through all the enclosures while also skipping the mask environment, so we couldn't just rely on `Rf_findFun`.  I'm also not a huge fan of how the KEEP/FREE business ended up in `findTilde`, but I didn't want to resort to more complex PROTECT stack management (that I'm less familiar with).
Note this does not correctly resolve things like `get('~')` which will return the Rlang tilde.  I tested this with valgrind, SAN, and rchk.  For rchk, there are errors, but they appear to be from code I did not touch:
```
Function mask_find
[UP] protect stack is too deep, unprotecting all variables, results will be incomplete
[UP] calling allocating function r_eval with a fresh pointer (obj <arg 1>) …
```
> Issue924: Resolve Normal Tilde's in Quosures

- R/arg.R
- R/call.R
- R/eval.R
- src/export/init.c
- src/internal/arg.c
- src/internal/call.c
- src/internal/eval.c
for functions called via `.External2()` .
(Where is that documented? WRE doesn't mention it.)
> Use rlang_ext2_* prefix consistently

- R/compat-lifecycle.R
I noticed that this didn't namespace prefix everything that comes from rlang
> Namespace prefix all rlang functions in `compat-lifecycle.R`

- R/compat-lifecycle.R
Missed one. This was caught by R cmd check and no others were flagged so it should be the last one
> Namespace prefix `ns_env()` in `lifecycle-compat.R`

- NEWS.md
- R/cnd-abort.R
- R/cnd-error.R
- R/utils.R
- man/abort.Rd
- tests/testthat/output-cnd-abort-parent-trace.txt
- tests/testthat/output-cnd-abort-trace-reminder.txt
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-cnd-error-parent-default.txt
- tests/testthat/test-cnd-error-parent-full.txt
- tests/testthat/test-cnd-error-parent-trace.txt
- tests/testthat/test-cnd-error-str.txt
- tests/testthat/test-with-abort.txt
* We now climb the ancestry of chained errors to find the oldest parent errors carrying a backtrace and display this backtrace in full. This is the oldest and thus most complete backtrace.
* We no longer decompose backtraces across error contexts because there is no way for us to do this with calling handlers. Calling handlers are now the preferred methods of rethrowing errors because they preserve the stack and allow users to `recover()` the error.
* The combination of these two changes produces consistent error and backtrace output for errors rethrown from both `tryCatch()` and `withCallingHandlers()`.
* The error ancestry is reflected with a tree display for error messages. The first message for the youngest error (highest level) is generated with `conditionMessage()`. The messages for …
> Review display of chained errors

- NEWS.md
- R/state.R
- man/is_interactive.Rd
Closes #1031
The original inclusion was inspired by code in readxl and readr that controls progress. However, in that case, the motivation is about performance, not about lack of interactivity *per se*.
RStudio sets "rstudio.notebook.executing" in notebooks AND whenever "Chunk output inline" is selected. Therefore this check makes code fail mysteriously in what seems to be an interactive session. First noticed in gargle/googlesheets4, where this prevented user interaction re: auth.
> Do not consult "rstudio.notebook.executing" option in `is_interactive()`

- NEWS.md
- R/cnd-abort.R
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-cnd-error-empty.txt
- tests/testthat/test-cnd-error-parent-default.txt
- tests/testthat/test-cnd-error.R
- tests/testthat/test-cnd-error.txt
> Avoid truncating backtraces in non-interactive sessions

- R/cnd-abort.R
- R/cnd-error.R
- R/trace.R
- tests/testthat/output-cnd-abort-parent-trace.txt
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-trace.R
And don't use them to trim the signalling context.
cc @gaborcsardi
> Don't store `ids` field in backtraces

- DESCRIPTION
- NEWS.md
- R/trace.R
- tests/testthat/test-trace.R
This is for capturing a native stack trace when the error occurs. See the examples at https://github.com/r-prof/winch/pull/4/checks?check_run_id=961027969#step:10:28 and below. I hope to get better native stack traces with libunwind (https://github.com/r-prof/winch/issues/2), I rather like how this seems to work already in all cases (`stop()`, `Rf_error()` and `abort()`).
Would you support this in rlang? I understand that we want to document and stabilize the structure of the `"rlang_trace"` before exposing it, and that we need tests. I don't mind marking this as "experimental".
> Optionally call winch::winch_add_trace_back() when collecting stack trace

- NEWS.md
- R/cnd-entrace.R
- tests/testthat/helper-rlang.R
- tests/testthat/test-cnd-entrace.R
Fixes rstudio/bookdown#920
Closes #1052
> Preserve exit status when `entrace()` is used as handler

- NEWS.md
- src/internal/eval-tidy.c
- src/lib/c-utils.h
Closes #1048. Performance is improved but not dramatically.
```r
data <- as.list(set_names(1:1e5))
bench::mark(before = as_data_mask(data))[1:8]
```
Before
```r
#>   expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
#> 1 before        220ms    223ms      4.47    5.44MB        0     3     0
```
After
```r
#>   expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
#> 1 after         169ms    170ms      5.88    2.76MB        0     3     0
```
For 1e6 elements this goes from 2.35s to 1.85s.
> Initialise data mask with expected number of elements

- NEWS.md
- R/eval-tidy.R
- R/lifecycle-retired.R
- src/export/init.c
- src/internal/eval-tidy.c
- tests/testthat/test-cnd-handlers.R
- tests/testthat/test-eval-tidy.R
> Propagate visibility in `eval_tidy()`

- R/cnd-entrace.R
- man/entrace.Rd
IIUC it's safe to just set
```
options(error = rlang::entrace)
```
and other parts of the codebase recommend + use this, so advocate using that directly here as well.
> advocate use of 'rlang::entrace' directly in docs

- tests/testthat/test-call.R
- tests/testthat/test-quo.R
- tests/testthat/test-vec-squash.R
> Fix warning regarding partial matching

- NEWS.md
- R/deparse.R
- tests/testthat/test-deparse.R
to avoid parser error when reparsing.
It's using a hammer, let me know if we can do better here.
Closes #1072.
> Deparse double and triple colon on the same line

- NEWS.md
- src/internal/hash.c
Hopefully fixes this gcc11 warning:
https://www.stats.ox.ac.uk/pub/bdr/gcc11/rlang.out
I think the problem comes with casting the `void*` to a `int*` to extract out the `int` representing the native encoding size that we know is there. The `void*` is probably really a `unsigned char*` under the hood, and gcc11 is probably picking up that it looks like we are trying to extract an `int` from an `unsigned char*`?
The fix here copies what R does in `R_Unserialize()` to get at that native encoding size. They use a `memcpy()` in `InBytes()` to just copy over the bytes directly into an `int`.
https://github.com/wch/r-source/blob/d22ee2fc0dc8142b23eed9f46edf76ea9d3ca69a/src/main/serialize.c#L421
https://github.com/wch/r-source/blob/d22ee2fc0dc8142b23eed9f46edf76ea9d3ca69a/src/main/serialize.c#L276 …
> Use `memcpy()` to copy over the native encoding size

- src/internal/hash.c
Should fix this gcc warning that @lionel- is seeing:
```c
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/string.h:190,
from ./rlang/vec.h:4,
from ./rlang/rlang.h:38,
from internal/internal.c:1,
from internal.c:1:
In function 'hash_skip',
inlined from 'hash_bytes' at internal/hash.c:182:5,
inlined from 'hash_char' at internal/hash.c:200:3:
internal/hash.c:216:5: warning: '__builtin_memcpy' forming offset [1, 3] is out of the bounds [0, 1] of object 'byte' with type 'unsigned char' [-Warray-bounds]
216 |     memcpy(&p_state->n_native_enc, p_input, sizeof(int));
|     ^~~~~~
In file included from internal/internal.c:16,
from internal.c:1:
internal/hash.c: In function 'hash_char':
internal/hash.c:198:17: note: 'byte' declared here
198 |   unsigned …
```
> Make `hash_char()` error, since it should never be called

- R/c-lib.R
- R/rlang.R
- src/Makevars
- src/export/exported.c
- src/export/init.c
- src/rlang/decl/dict-decl.h
- src/rlang/dict.c
- src/rlang/dict.h
- src/rlang/rlang.c
- src/rlang/rlang.h
- src/rlang/sexp.c
- src/rlang/sexp.h
- tests/testthat/test-c-api.R
* `r_preserve()` now uses a dictionary to preserve objects. This should guarantee constant time insertion and deletion.
* The dictionary is protected from the embedding namespace. This way, unloading the namespace automatically unprotects all preserved objects.
* `r_init_library()` now takes a namespace as argument. This should be the embedding namespace not the rlang namespace. The namespace must be unsealed at the time of calling because a new binding is added to store the dictionary of precious objects.
* Add `dict_del()` method to remove objects from the dictionary. This is used in `r_unpreserve()`.
> Preserve objects in a namespace-bound dictionary

- R/c-lib.R
- src/export/exported.c
- src/export/init.c
- src/rlang/decl/sexp-decl.h
- src/rlang/dict.c
- src/rlang/dict.h
- src/rlang/sexp.c
- tests/testthat/test-c-api.R
Follow up to #1096. We need a stack of protection so that `r_preserve()` and `r_unpreserve()` may be called independently in unrelated contexts.
Also adds `r_dict_get0()` which is a variant of `r_dict_get()` that returns a C `NULL` instead of throwing an error when the key does not exist in the dictionary. This avoids an extra lookup in the case the key exists because we no longer need to call `r_dict_has()` before `r_dict_get()`.
> Use dictionary of stacks for preserving objects

- R/hash.R
- man/hash.Rd
- tests/testthat/helper-rlang.R
- tests/testthat/test-hash.R
Closes #1084 
Closes #1086 
Ultimately, we have decided that the work in #1086 to switch to using XDR format to generate hashes that are independent of endianness is not worth it, due to the large performance impact that comes from switching from binary -> XDR.
This PR skips the `hash()` tests on big-endian platforms, and updates the documentation to note that both the R version and endianness must be the same to generate identical hashes.
> Adjust `hash()` tests to skip on big endian platforms

- R/c-lib.R
- src/export/exported.c
- src/export/init.c
- src/rlang/dyn-array.c
- src/rlang/dyn-array.h
- src/rlang/sexp.c
- src/rlang/sexp.h
- src/rlang/vec.h
- tests/testthat/test-c-api.R
Turns out it was easy to adapt the dynamic arrays implemented in #1107 to support all sorts of vectors.
> Support atomic and barrier vectors in dynamic arrays API

- NEWS.md
- src/capture.c
- tests/testthat/test-nse-defuse.R
Closes #1137
Step towards tidyverse/dplyr#5815
`enquo(..1)` and `enquos(...)` with numbered dots supplied within `...` now properly capture the underlying expressions and environments. This allows new metaprogramming patterns based on `match.call()`. For an example see https://github.com/tidyverse/dplyr/pull/5815/commits/d4fd1e0f.
> Defuse numbered dots

- src/rlang/rlang.h
Specifically, to avoid:
```c
In file included from internal.c:12:
internal/hash.c: In function 'hash_impl':
internal/hash.c:142:16: warning: unknown conversion type character 'l' in format [-Wformat=]
142 |   sprintf(out, "%016" PRIx64 "%016" PRIx64, high, low);
|                ^~~~~~
In file included from ./lib/rlang.h:5,
from internal/arg.c:1,
from internal.c:1:
c:\msys64\home\tomas\ucrt3\svn\ucrt3\r_packages\x86_64-w64-mingw32.static.posix\include\inttypes.h:37:18: note: format string is defined here
37 | #define PRIx64 "llx"
|                  ^
In file included from internal.c:12:
internal/hash.c:142:16: warning: unknown conversion type character 'l' in format [-Wformat=]
142 |   sprintf(out, "%016" PRIx64 "%016" PRIx64, high, low);
|                ^~~~~~
In file included from …
```
> Define `_ISOC99_SOURCE` to avoid warnings on CRAN's UCRT machine

- NEWS.md
- R/cnd-message.R
- R/utils.R
- man/format_error_bullets.Rd
- tests/testthat/test-cnd-message.R
Packages generally prefix messages with one of four bullets: a star, an info "i", a cross, and a tick.
For example, `usethis` offers `ui_todo()`, `ui_info()`, `ui_oops()` and `ui_done()`.
Currently, `format_error_bullets()` only offers a star, info symbol and cross.
This PR adds a green tick bullet when the element name is `"v"`, matching current usage where a cross is used for elements named `"x"` and an info symbol for elements named `"i"`.
> Add tick as a bullet type in format_error_bullets()

- NEWS.md
- R/deparse.R
- R/expr.R
- R/quo.R
- man/expr_print.Rd
- tests/testthat/test-deparse.R
I maintain the [tidyquery](https://github.com/ianmcook/tidyquery) package which uses `rlang::expr_deparse()` to power the `show_dplyr()` function. I would like to be able to disable the truncation of deparsed vectors and lists. This PR adds a new argument `max_len` (edit: renamed `max_elements`) to control this. Thank you!
> Parameterize truncation when deparsing vectors and lists

- NEWS.md
- R/compat-purrr.R
- R/lifecycle-retired.R
- tests/testthat/test-compat-purrr.R
- tests/testthat/test-retired.R
* Remove pluck functions (fixes #1159)
* Remove `map_cpl()` and `map2_cpl()`
* Use `as_function()` (fixes #1157)
I didn't namespace because all the options I tried looked ugly.
> compat-purrr.R tweaks

- R/dots.R
- man/dyn-dots.Rd
- tests/testthat.R
Checks should give only NOTEs about missing suggested packages.  
- Since `roxygen2` needs `glue`, we need to update docs before getting rid of `glue`.
- Since `testthat` needs `glue`, we also have to assume it isn't installed.  
- Since `devtools` needs `glue`, we need to do our checks using standard `R CMD check`.
This PR fixes issue #1178 in that `rlang` can pass CRAN checks without ERRORs or WARNINGs if `glue` is missing, but I don't know if it will still install on winUCRT, because I don't have a test platform set up for that yet.
> If `glue` is not installed, `rlang` should still be installable

- NEWS.md
- R/compat-s3-register.R
- tests/testthat/_snaps/compat-s3-register.md
- tests/testthat/test-compat-s3-register.R
Turns out we had disparate code paths, in some cases we threw an error but not others. This is now fixed through a closure that is called in both cases.
Following Slack discussion, we still warn if `NOT_CRAN` is set in case the developer misspelled the generic. I think this warning will only show up when the namespace gets loaded during tests, but I'm not sure how we can do better.
Closes #1112.
> Don't throw error from `s3_register()` if generic does not exist

- NEWS.md
- R/cnd-abort.R
- R/cnd-signal.R
- man/abort.Rd
- tests/testthat/test-cnd-signal.R
> Add global options to silence messages and warnings

- NEWS.md
- R/arg.R
- man/arg_match.Rd
- src/Makevars
- src/internal/arg.c
- src/internal/decl/arg-decl.h
- src/internal/decl/dots-decl.h
- src/internal/dots.c
- src/internal/init.c
- src/rlang/arg.c
- src/rlang/arg.h
- src/rlang/rlang.c
- src/rlang/rlang.h
- tests/testthat/_snaps/arg.md
- tests/testthat/_snaps/dots.md
- tests/testthat/test-arg.R
- tests/testthat/test-dots.R
Closes #1163.
Takes same inputs as `arg_match0()` at R level. Returns an int that can be coerced to an enum (see changes in `dots.c`).
> Include `r_arg_match()` in C library

- src/Makevars
- src/internal/decl/encoding-decl.h
- src/internal/encoding.c
- src/internal/encoding.h
- src/internal/init.c
- src/internal/internal.c
- src/rlang/obj.c
- src/rlang/obj.h
- tests/testthat/_snaps/c-api.md
- tests/testthat/helper-c-api.R
- tests/testthat/test-c-api.R
Pulled over from https://github.com/r-lib/vctrs/blob/master/src/translate.c
I've left in the maybe-referenced copy semantics, as that seems to work best with vctrs.
Otherwise, I've done minor tweaks to use more of the rlang lib, but nothing major.
I've pulled in all the relevant tests from vctrs, with a few testthat utilities. There are quite a few tests, but I went through each one and none of them feel redundant. I think they are required to ensure we hit all the code paths, but we could move them out of `test-c-api.R` if you feel it clutters it too much.
> Implement `r_normalise_encoding()`

- R/cnd-signal.R
https://github.com/r-lib/rlang/pull/1188 removed support for `rlang:::message_always`. 
Currently, CRAN version of `shiny` has a test that is using this option.  The test has been updated https://github.com/rstudio/shiny/pull/3379 for the next regular release of shiny.
I suggested a date of 2022. Shiny should be released by then. Feel free to change the comment / time.
-----------------
If you'd rather not take the PR, we could make a patch release for `shiny` to disable the test. I'd prefer to **not** go down that route.
Thank you!
cc @cpsievert
> Add legacy support for `peek_option("rlang:::message_always")`

- NEWS.md
- R/attr.R
- R/nse-defuse.R
- man/exprs_auto_name.Rd
- tests/testthat/_snaps/nse-defuse.md
- tests/testthat/test-nse-defuse.R
Branched from #1193.
Closes #1116.
`exprs_auto_name()` gains a `repair_auto` argument to repair the automatic names. The non-automatic names are never repaired (if that is needed, just repair the whole vector separately):
```r
dots_names <- function(...) {
dots <- enquos(...)
dots <- exprs_auto_name(dots, repair_auto = "unique")
names(dots)
}
dots_names(bar, foo = 1, bar, foo = 2)
#> New names:
#> • `bar` -> `bar...1`
#> • `bar` -> `bar...3`
#> [1] "bar...1" "foo"     "bar...3" "foo"
```
The message can be disabled with the `repair_quiet` argument. Currently only unique repairing is possible as universal repairing is still implemented in vctrs.
Because of potential issues of backward-compatibility , the default is set to `"minimal"`, the same behaviour as before. This way we can try out …
> Add `repair_auto` and `repair_quiet` to `exprs_auto_name()`

- R/compat-downstream-dep.R
- R/rlang.R
User is now prompted to update outdated dependencies when they are loaded in the session:
```r
As of rlang 0.4.11.9000, pkgFoo must be at least version 1.0.0.
x pkgFoo 0.1.0 is too old for rlang 0.4.11.9000.
! Would you like to update the package pkgFoo now?
1: Yes
2: No
Selection: 
```
If they accept, the package is installed with pak if available. If they decline, they are informed about a global option to turn off the checks. This should be useful for users who are not able to update right away:
```r
> Selection: 2
Set `options(rlib_downstream_check = FALSE)` to disable this prompt.
```
In non-interactive sessions, the usual warning is displayed:
```r
Warning message:
As of rlang 0.4.11.9000, pkgFoo must be at least version 1.0.0.
x pkgFoo 0.1.0 is too old for rlang 0.4.11.9000.
i …
```
> Prompt user for outdated downstream deps

- NEWS.md
- R/cnd-abort.R
- man/abort.Rd
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/trace.md
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-cnd-error.R
- tests/testthat/test-trace-full.Rmd
- tests/testthat/test-trace.R
- tests/testthat/test-trace.Rmd
This method consults `rlang_backtrace_on_error` to determine whether to display a backtrace with the error message. Whereas the default value for this option is `"reminder"` in interactive sessions and `"full"` in non-interactive sessions, the default is set to `"none"` in knitr chunks that expect errors (`error = TRUE` chunks).
The method also sets `rlang::last_error()`. Consulting the last error must be done in a different chunk since the `sew()` generic is run at the end of a chunk.
This should fix all corner cases regarding backtrace handling in `reprex::reprex()`. Closes #1205. cc @jennybc.
I will also look into setting `rlang_trace_top_env` from knitr. Would there be a downside to do this @hadley?
> Register an `rlang_error` method for `knitr::sew()` to handle backtraces in error messages

- NEWS.md
- R/cnd-abort.R
- R/cnd-signal.R
- man/abort.Rd
- tests/testthat/test-cnd-signal.R
> Set `warning.length` to maximum value before throwing or warning

- R/compat-purrr.R
- R/utils.R
- tests/testthat/test-compat-purrr.R
> compat-purrr.R: fix typo in `imap()`

- src/rlang/c-utils.h
> Fix bug in overflow condition of `r__intmax_subtract()`

- NEWS.md
- R/expr.R
- R/utils.R
- man/is_expression.Rd
- tests/testthat/test-expr.R
This makes `is_expression()` in line with the documented definition. It also makes it more useful as it can now be used to detect calls that can't be roundtripped with parse/deparse.
This is implemented using iteration instead of recursion, using a dynamic stack whose `pop()` method is a coro generator as outlined in https://github.com/r-lib/rlang/issues/1129#issuecomment-874224656.
> Make `is_expression()` recursive over calls

- R/compat-cli.R
- tests/testthat/_snaps/compat-cli.md
- tests/testthat/test-compat-cli.R
* Add `ansi_` functions for colours and typography.
* Add `symbol_` and corresponding `ansi_` functions for unicode symbols. The `ansi_` variants apply a default colour to the symbol (e.g. red for crosses).
Some of the functions prefixed with `ansi_` in the compat file are prefixed with `style_` in the cli API. This inconsistency is deliberate because  #1213 reserves the `style_` prefix for styler functions that must be paired with a cli-formatting function.
> Flesh out `compat-cli.R`

- DESCRIPTION
- NEWS.md
- R/cnd-abort.R
- R/cnd-error.R
- R/cnd-message.R
- man/abort.Rd
- src/version.c
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-error.md
- tests/testthat/helper-rlang.R
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-cnd-error.R
- tests/testthat/test-cnd-message.R
To support https://github.com/tidymodels/recipes/pull/734 (cc @DavisVaughan).
1. Display the whole message ourselves including the `Error: ` prefix. This removes the limitation on the length of error messages (the limit can easily be reached because of ANSI markup by cli). This also makes it possible to format calls according to our standards.
2. Include `call` fields in error prefixes if present. Complex calls containing inlined objects are ignored and the arguments of the call are stripped to keep it simple. The call is formatted as code using cli if available. Unlike `stop(call. = TRUE)`, there is no space after `:`.
```r
abort("msg", call = quote(foo(bar, baz)))
#> Error in `foo()`: msg
```
Rethrowing with a context added in `call` field:
```r
f <- function() g()
h …
```
> Handle `call` fields in errors

- R/arg.R
- man/arg_match.Rd
While the docs say
> This is equivalent to `base::match.arg()`
it is not obvious that `rlang::arg_match()` should only be used when the argument takes character values.
> better arg_match description

- src/internal/dots-ellipsis.c
- src/internal/exported.c
- src/rlang/rlang.c
- src/rlang/rlang.h
- src/rlang/vec.h
To allow for customizing the argument name in error messages
> Implement `r_arg_as_*()` helpers

- R/names.R
- man/names_inform_repair.Rd
- tests/testthat/_snaps/nse-defuse.md
- tests/testthat/test-names.R
This also adds the `"rlib_message_name_repair"` class to the message signaled by `names_inform_repair()`, giving us yet another method to handle it.
I did not add a NEWS bullet because there isn't one for `names_inform_repair()` being a new function.
_Side note:_ Should this function be named `inform_name_repair()`? We normally use `stop_*()` and `warn_*()` elsewhere for our error/warning naming conventions, and that form matches the global option / class name better.
> Allow `names_inform_repair()` to be silenced by a global option

- R/env-binding.R
- src/internal/env-binding.c
- src/rlang/eval.c
- src/rlang/eval.h
- tests/testthat/_snaps/env-binding.md
- tests/testthat/test-env-binding.R
Previously:
```r
env_get(nm = "foobar")
#> Error in env_get(nm = "foobar") : 
#>   argument "default" is missing, with no default
```
Now:
```r
env_get(nm = "foobar")
#> Error: Can't find `foobar` in environment.
```
> Use error style guide in `env_get()` error for missing binding

- NEWS.md
- R/cnd-abort.R
- R/cnd-error.R
- R/cnd-message.R
- tests/testthat/_snaps/arg.md
- tests/testthat/_snaps/attr.md
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-entrace.md
- tests/testthat/_snaps/cnd-error.md
- tests/testthat/_snaps/cnd-message.md
- tests/testthat/_snaps/dots-ellipsis.md
- tests/testthat/_snaps/dots.md
- tests/testthat/_snaps/env-binding.md
- tests/testthat/_snaps/fn.md
- tests/testthat/_snaps/operators.md
- tests/testthat/_snaps/session.md
- tests/testthat/_snaps/trace.md
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-cnd-error.R
- tests/testthat/test-cnd-message.R
Display call inline when printing errors (e.g. by calling `last_error()`). Closes #1259.
```r
f <- function() g()
h <- function() rlang::abort("Low-level.")
f()
#> Error in `h()`: Low-level.
#> Run `rlang::last_error()` to see where the error occurred.
last_error()
#> <error/rlang_error>
#> Low-level.
#> Call: `h()`
#> Backtrace:
#>  1. global::f()
#>  2. global::g()
#>  3. global::h()
#> Run `rlang::last_trace()` to see the full context.
last_error()
#> <error/rlang_error>
#> Error in `h()`: Low-level.
#> Backtrace:
#>  1. global::f()
#>  2. global::g()
#>  3. global::h()
#> Run `rlang::last_trace()` to see the full context.
```
With chained errors:
```r
a <- function() b()
b <- function() c()
c <- function() {
withCallingHandlers(
error = function(cnd) { …
```
> Improve display of chained errors

- NEWS.md
- R/cnd-abort.R
- R/cnd-message.R
- R/eval.R
- R/trace.R
- R/utils-cli-tree.R
- R/utils.R
- man/abort.Rd
- tests/testthat/_snaps/cnd-message.md
- tests/testthat/_snaps/trace.md
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-cnd-message.R
- Add a line break between the error prefix (the "Error:" part) and the error message when the former gets too long. A long prefix is currently defined as longer than half the screen width or when a source location is included.
- Add srcref information in the error prefix (closes #1260). This is not displayed when testthat is running to avoid making snapshots brittle. testthat provides source locations for unexpected errors and warnings via other means.
- Add an "Error prefix:" section in `?abort`.
- Include srcrefs on their own lines in simplified backtraces.
- Use "at" to introduce srcrefs in backtraces, consistently with the error prefix.
```r
rlang:::eval_parse("{
f <- function() g()
h <- function() abort('Foo.')
}")
src_file <- h %@% srcref %@% srcfile …
```
> Display source locations in error messages

- NEWS.md
- R/cnd-abort.R
- R/cnd-error.R
- R/cnd-message.R
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-entrace.md
- tests/testthat/_snaps/cnd-error.md
- tests/testthat/test-cnd-error.R
And indent error messages when printing a chain of errors.
The display is unchanged in the normal case:
```r
f <- function() g()
h <- function() rlang::abort("Low-level.")
f()
#> Error in `h()`: Low-level.
last_error()
#> <error/rlang_error>
#> Error in `h()`: Low-level.
#> Backtrace:
#>  1. global::f()
#>  2. global::g()
#>  3. global::h()
```
If the error is part of a chain, all parent causes are displayed with indentation:
```r
a <- function() b()
b <- function() c()
c <- function() {
withCallingHandlers(
error = function(cnd) {
rlang::abort(
"High-level",
parent = cnd,
call = env_parent()
)
},
f()
)
}
a()
#> Error in `c()`:
#>   High-level
#> Caused by error in `h()`:
#>   Low-level.
last_error()
#> <error/rlang_error>
#> Error in `c()`:
#>   High-level
#> Caused …
```
> Print parent errors at throw time

- R/cnd-abort.R
- R/trace.R
- man/abort.Rd
- man/last_error.Rd
- man/rlang_backtrace_on_error.Rd
- man/trace_back.Rd
I couldn't re-build the docs because `load_all()` gives me:
```
Error in new_weakref(env, finalizer = ns_finalizer(dll_path)) : 
object 'rlang_new_weakref' not found
Calls: suppressPackageStartupMessages ... load_code -> <Anonymous> -> load_dll -> new_weakref
Execution halted
```
> More clearly cross-reference rlang_backtrace_on_error

- NEWS.md
- R/cnd-abort.R
- R/cnd-error.R
- R/trace.R
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-entrace.md
- tests/testthat/_snaps/cnd-error.md
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-cnd-entrace.R
- tests/testthat/test-cnd-error.R
- tests/testthat/test-trace.R
And make trace capture in wrapped rethrowing handlers more robust.
Closes #1098.
> Display external backtraces

- NEWS.md
- R/call.R
- R/cnd-abort.R
- R/trace.R
- tests/testthat/_snaps/cnd-entrace.md
- tests/testthat/_snaps/trace.md
- tests/testthat/test-call.R
- tests/testthat/test-trace.R
Closes #1069.
Closes r-lib/testthat#1223.
Inline objects are replaced by their pillar type sum:
```r
call <- expr(foo(!!(1:2)))
call_zap_inline(call)
#> foo(`<int>`)
```
> Zap inline objects from backtraces

- NEWS.md
- R/trace.R
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-entrace.md
- tests/testthat/_snaps/cnd-error.md
- tests/testthat/_snaps/cnd-signal.md
- tests/testthat/_snaps/trace.md
@jimhester makes a good point that it's confusing to display namespaced calls in the backtrace that don't work in the console. This PR leverages the new metadata recorded in backtraces to replace namespace operators with a simple space. Closes #902.
Local functions are no longer qualified with `:::`
```r
as.Date("foo")
#> Error in charToDate(x) :
#>   character string is not in a standard unambiguous format
last_error()
#> <error/rlang_error>
#> Error: character string is not in a standard unambiguous format
#> Backtrace:
#>  1. base::as.Date(...)
#>  2. base::as.Date.character(...)
#>  3. base:::charToDate(...)
last_error()
#> <error/rlang_error>
#> Error: character string is not in a standard unambiguous format
#> Backtrace:
#>  1. base::as.Date(...)
#>  2. base::as.Date.character(...) …
```
> Don't use namespace operators invalidly

- R/c-lib.R
I'm pretty sure we need to pass through the project path in `has_cpp11_sysreq()`.
Also, `grep()` doesn't like the `++` in the `"C++11"` pattern and returns this without `fixed = TRUE`:
```r
Error in grepl("C++11", desc_lines, fixed = F) : 
invalid regular expression 'C++11', reason 'Invalid use of repetition operators'
```
> Fix C++11 detection in `use_rlang_c_library()`

- NEWS.md
- R/dots-ellipsis.R
- man/check_dots_empty.Rd
- man/check_dots_unnamed.Rd
- man/check_dots_used.Rd
- tests/testthat/test-dots-ellipsis.R
To avoid tying the ellipsis functions to a fuzzy signaller interface (e.g. does the signaller support `call` arguments?).
Also more consistent with general condition handling idioms.
> Replace `action = signaller` arguments by `error = handler`

- _pkgdown.yml
The new reference index looks great! I noticed this while there.
> Typo fix (and, apparently, some whitespace)

- tests/testthat/test-deparse.R
In my original attempt at #1299, I truncated the left side before checking the right, but before merging @lionel- improved that to keep the left side intact if possible. That meant that the comment I left describing one of the tests wasn't accurate anymore.
> Fix comment in test following #1299

- NEWS.md
- R/cnd-abort.R
- R/cnd-message.R
- R/cnd.R
- man/cnd_message.Rd
- man/topic-data-mask-programming.Rd
- man/topic-data-mask.Rd
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-message.md
- tests/testthat/fixtures/error-backtrace-conditionMessage.R
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-cnd-message.R
- tests/testthat/test-parent-errors.Rmd
Part of r-lib/testthat#1493. Since the parent messages are included, it is now possible to match them.
Also fixes chained error messages in knitr/rmarkdown. The output is not optimal but much better and good enough as a stopgap until knitr is able to use `cnd_message()` or equivalent.
> Include parent messages in `cnd_message()`

- DESCRIPTION
- NEWS.md
- R/compat-purrr.R
- R/session.R
- R/vec-na.R
- man/is_installed.Rd
- src/version.c
- tests/testthat/_snaps/session.md
- tests/testthat/test-compat-purrr.R
- tests/testthat/test-session.R
Branched from #1331.
* DESCRIPTION-style requirements are now supported, e.g. `is_installed("rlang (>= 1.0.0)"`.
* New `compare` argument to supply requirement info programmatically.
* When `<` or `<=` is used, `check_installed()` doesn't prompt for install.
This will allow support for `check_installed()` in pkgload, so that we get install prompts on missing deps.
> Improve version requirements in `is_installed()` and `check_installed()`

- R/cnd-abort.R
- R/deparse.R
- R/utils.R
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-entrace.md
- tests/testthat/_snaps/cnd-message.md
- tests/testthat/_snaps/operators.md
- tests/testthat/_snaps/trace.md
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-cnd-message.R
- tests/testthat/test-deparse.R
```r
1 + ""
#> Error in `1 + ""`:
#> non-numeric argument to binary operator
```
Multiline operators are printed with indentation:
```r
err <- function(expr) error_cnd(message = "This is the error message.", call = enexpr(expr))
err(1 + ("veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery_long" + "veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery_long"))
#> <error/rlang_error>
#> Error in `1 + ("veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery_long" +
#>     "veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery_long")`:
#> This is the error message.
err({ 1; 2 } + { 2; 3 })
#> <error/rlang_error>
#> Error in `{
#>     1
#>     2
#>   } + {
#>     2
#>     3
#>   }`:
#> This is the error message.
err(x[{ 1; 2 }])
#> <error/rlang_error>
#> Error in `x[{
#>     1
#>     2
#>   }]`:
#> This is the error message.
```
> Fully preserve operators in error calls

- R/dots-ellipsis.R
- src/internal/dots-ellipsis.c
- src/internal/init.c
- tests/testthat/_snaps/dots-ellipsis.md
- tests/testthat/test-dots-ellipsis.R
Closes #1319.
In all ellipsis errors:
* Show the value of the arguments.
* Try to reduce text density.
* Use conventional "must be" or "can't" phrasing.
In empty dots errors:
* Don't mention "future extensions", just that no arguments are expected in `...`.
* Suggest user has probably forgotten to give a name to an argument when unnamed dots are supplied and dots should be empty.
Before:
```r
is_installed("rlang", "0.99.0.9001")
#> Error in `is_installed()`: `...` is not empty.
#> i These dots only exist to allow future extensions and should be empty.
#> x We detected these problematic arguments:
#> * `..1`
#> i Did you misspecify an argument?
```
After:
```r
is_installed("rlang", "0.99.0.9001")
#> Error in `is_installed()`:
#> `...` must be empty.
#> x Problematic argument:
#> * ..1 = …
```
> Improve ellipsis errors

- R/cnd-message.R
- R/cnd.R
- man/topic-data-mask-programming.Rd
- man/topic-data-mask.Rd
- tests/testthat/_snaps/arg.md
- tests/testthat/_snaps/attr.md
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-entrace.md
- tests/testthat/_snaps/cnd-handlers.md
- tests/testthat/_snaps/cnd-message.md
- tests/testthat/_snaps/cnd-signal.md
- tests/testthat/_snaps/cnd.md
- tests/testthat/_snaps/compat-downstream-deps.md
- tests/testthat/_snaps/compat-s3-register.md
- tests/testthat/_snaps/dots-ellipsis.md
- tests/testthat/_snaps/dots.md
- tests/testthat/_snaps/env-binding.md
- tests/testthat/_snaps/eval-tidy.md
- tests/testthat/_snaps/fn.md
- tests/testthat/_snaps/nse-force.md
- tests/testthat/_snaps/operators.md
- tests/testthat/_snaps/session.md
- tests/testthat/_snaps/trace.md
- tests/testthat/_snaps/types.md
- tests/testthat/test-cnd-message.R
* Use `!` bullet for error headers and for all parent headers
* Remove indent in chained errors
We can't use `!` for warnings because there is no straightforward way of decoupling this style from `conditionMessage()`, since we don't control output for warnings. Given the above two changes, we get slightly suboptimal output in some cases, e.g.:
```r
parent <- error_cnd(message = "This is an error.")
warn("This is a warning.", parent = parent)
#> Warning message:
#> This is a warning.
#> Caused by error:
#> ! This is an error.
parent <- warning_cnd(message = "This is a warning.")
abort("This is a message.", parent = parent)
#> Error:
#> ! This is a message.
#> Caused by warning:
#> ! This is a warning.
```
> Use alert bullets in error messages

- NEWS.md
- R/arg.R
- R/cnd-abort.R
- R/utils.R
- man/abort.Rd
- tests/testthat/_snaps/arg.md
- tests/testthat/_snaps/c-api.md
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/test-c-api.R
- tests/testthat/test-cnd-abort.R
And use it in `arg_match()`.
Making it an argument to `abort()` will be useful with input checkers. For instance, checkers can take `...` to be passed on to `abort()`, and then internal errors can be signalled as
```r
check_bool(x, .internal = TRUE)
```
> Add `.internal` argument to `abort()`

- R/compat-friendly-type.R
- R/lifecycle-retired.R
- R/utils.R
- tests/testthat/_snaps/eval-tidy.md
- tests/testthat/_snaps/fn.md
- tests/testthat/test-bytes.R
- tests/testthat/test-env.R
- tests/testthat/test-eval-tidy.R
- tests/testthat/test-friendly-type.R
- tests/testthat/test-retired.R
- tests/testthat/test-vec-new.R
Branched from #1334.
New `value` argument that controls whether to be more informative about the input type. When set, we mention whether the input is a missing value, a scalar value, or an empty value.
In the future, I think we should show the contents of scalar values, but this will be tackled another time.
> Improve `friendly_type_of()`

- src/internal/cnd-handlers.c
- src/internal/dots.c
- src/internal/encoding.c
- src/internal/replace-na.c
- src/rlang/dyn-array.h
- src/rlang/globals.c
- src/rlang/globals.h
- src/rlang/rlang-types.h
- src/rlang/vec.c
- src/rlang/vec.h
For consistency with `r_ssize`, `r_obj`, etc., rename:
- `r_complex_t` to `r_complex`
- `r_keep_t` to `r_keep_loc`
> Don't use `_t` suffix

- R/c-lib.R
- Master has become main (it fails otherwise because `rlang-master` doesn't exist now)
- Fix small typo with Makvars->Makevars
> Fix rlang C library issues

- src/rlang/cpp/vec.cpp
- src/rlang/rlang.hpp
It is used in `rcc_abort()` below. The only reason this hasn't caused issues so far is because the only place this header is included is in `vec.cpp`, which includes `<algorithm>` first and that includes the exception header, so we don't see the issue
I have also flipped the order of includes in `vec.cpp` because I believe that including your own headers first is better practice. See also https://github.com/tidyverse/readxl/commit/1059a768436df38fb7b33f8e0415c18585c11ac5
> Include `<exception>` header in `rlang.hpp`

- src/rlang/rlang.hpp
- Added header guards
- Make `rcc_abort()` `static inline`, since it is defined in a header file
> Make `rlang.hpp` more inclusion friendly

- src/internal/dots.c
- src/internal/eval-tidy.c
- src/rlang/attrib.c
- src/rlang/attrib.h
- src/rlang/df.c
- src/rlang/dict.c
- src/rlang/dyn-array.c
- src/rlang/globals.c
- src/rlang/globals.h
- src/rlang/rlang.hpp
Follow up to https://github.com/r-lib/rlang/commit/70c90a8be9987c0b1fb96a74fd9d84d839b5d7ae and https://github.com/r-lib/rlang/commit/30cae2afc181c3ddfbb59a3fd5d323f919831413
We previously added workarounds to the fact that C++ doesn't like you to use `class` as a variable name at all by redefining it to `klass` before including `<rlang.h>`. This currently works, but I am afraid it is extremely brittle and is the reason for many other hacks we have had to do to make the C and C++ code here play nicely together.
I propose moving from `r_syms.class` to `r_syms.class_`, which is better than `cls` or `klass` because it works with auto-complete. That way in the future we won't ever think that we don't have a symbol for `class` and try and add one back in.
If you look at the `rlang.hpp` file …
> Rename `r_syms.class` to `r_syms.class_`

- NEWS.md
- R/call.R
- R/node.R
- R/trace.R
- src/internal/call.c
- src/internal/decl/call-decl.h
- src/internal/exported.c
- src/internal/init.c
- src/internal/internal.c
- src/internal/vec.c
- src/internal/vec.h
- src/rlang/call.c
- src/rlang/call.h
- tests/testthat/test-call.R
- tests/testthat/test-cnd-entrace.R
Avoid data frames in a few places, and rewrite `call_zap_inline()` and `is_call()` in C.
This shrinks the benchmark below from 20ms to 1.1ms. This is still twice as slow as before (604µs), but after that point it becomes hard to optimise. The perf difference is due to the improved detection of namespaces and scopes stored in the backtrace.
cc @hadley.
```r
f <- function(n) {
if (n) f(n - 1) else rlang::trace_back()
}
f(30)
bench::mark(f(30))[1:8]
#>   expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#> 1 f(30)        1.06ms   1.14ms      830.    13.1KB     19.1   390     9
#>   expression      min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#> 1 f(30)        2.65ms 2.72ms      338.    15.2KB     27.6   147    12
#>   expression      min median `itr/sec` mem_alloc …
```
> Fix trace creation performance regression

- tests/testthat/test-cnd-entrace.R
- tests/testthat/test-cnd-handlers.R
Using 4.0.0 here:
https://github.com/r-lib/rlang/blob/68f768deed899ddded2ea102217531bc6e5a0b1e/tests/testthat/test-env.R#L364
There are also usages skipping based on `getRversion`, e.g.:
https://github.com/r-lib/rlang/blob/68f768deed899ddded2ea102217531bc6e5a0b1e/tests/testthat/test-compat-vctrs.R#L348
Should we unify those as well?
----
Of course it's somewhat trivial, but the test output is a bit noisy with the inconsistency. e.g. here's running from 3.6.3:
```
══ Skipped tests ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
• Cannot set MBCS locale (1)
• !compiled_by_gcc() is TRUE (1)
• Disabled (1)
• Failing (1)
• getRversion() < "4.0" is TRUE (1)
• Installed base is version …
```
> use consistent formatting for base version skip

- R/nse-defuse.R
- man/exprs_auto_name.Rd
The current docs are pointing to questioning functions.
Should we soft-deprecate `quos_auto_name()`? It's forwarding to `exprs_auto_name()`, with fewer arguments.
> Update docs for exprs_auto_name()

- NEWS.md
- R/arg.R
- R/cnd-abort.R
- R/cnd-entrace.R
- R/cnd-message.R
- R/cnd-signal.R
- R/cnd.R
- R/compat-cli.R
- R/compat-obj-type.R
- R/deparse.R
- R/env-special.R
- R/trace.R
- R/utils.R
- man/abort.Rd
- tests/testthat/_snaps/arg.md
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-message.md
- tests/testthat/_snaps/trace.md
- tests/testthat/fixtures/error-backtrace-conditionMessage.R
- tests/testthat/helper-trace.R
- tests/testthat/test-arg.R
- tests/testthat/test-cnd-abort.R
- tests/testthat/test-cnd-message.R
- tests/testthat/test-cnd.R
- tests/testthat/test-trace.R
* When `call` is a frame environment, the corresponding function call is now highlighted in the backtrace.
* When a function argument for that function call is stored in the `arg` condition field, this argument is highlighted in the backtrace.
* A special cli theme is registered when printing the backtrace to highlight the calls and arguments. Calls are highlighted in bold bright blue, and args in bold bright magenta.
* The cli theme is only applied at print time. This means that input checking functions must format the error message lazily. To support this, `abort()` now accepts a `cnd_header()` method via the `message` argument.
* `arg_match()` and the internal checking functions (implemented via `stop_input_type()` from compat-friendly-type-of.R) now support this.
Before:
```r …
```
> Highlight call and argument in backtraces

- NEWS.md
- R/bytes.R
- R/compat-sizes.R
- man/bytes-class.Rd
- tests/testthat/_snaps/bytes.md
- tests/testthat/_snaps/dots.md
- tests/testthat/test-bytes.R
It would be nice to provide a global option to format bytes with binary prefixes. This requires https://github.com/r-lib/prettyunits/issues/29.
> Use prettyunits to format bytes

- R/arg.R
Hi, I just randomly stumbled upon this. I believe the intention was to return invisibly, however, that is not what R does:
```
f = function() invisible(return(5))
f()
f = function() return(invisible(5))
f()
##
```
`invisible` is a builtin that evaluates its arguments eagerly, and `return` uses a non-local jump to get out of the function, skipping the visibility change.
> Fix returning invisibly

- NEWS.md
- src/rlang/vec-lgl.c
- tests/testthat/test-c-api.R
- Cleaned up the style in `r_lgl_which()`
- Lifted the `na_propagate` branch out of the for loop
- Simplified the if condition, especially in the `na_propagate = FALSE` case
- Added in support for propagating names
I don't think this has much performance impact when there aren't names. In fact, it looks like moving the `na_propagate` branch out of the loop and simplifying the if condition has made things slightly faster in the `na_propagate = FALSE` case.
``` r
devtools::load_all()
#> ℹ Loading rlang
x <- sample(c(TRUE, FALSE, NA), size = 2e6, replace = TRUE)
bench::mark(
r_lgl_which(x, na_propagate = TRUE),
r_lgl_which(x, na_propagate = FALSE),
iterations = 500,
check = FALSE
)
#> # A tibble: 2 × 6
#>   expression                                min   median
#>   <bch:expr> …
```
> Propagate names through `r_lgl_which()`

- R/cnd-handlers.R
Should be as lean as possible.
I wonder if `try_catch()` could be implemented entirely from C via `R_tryCatch()` or `R_tryCatchError()`, or perhaps with new entry points. It seems that it's currently constructing R code of the form `tryCatch(withCallingHandlers(...))` (or just `withCallingHandlers(...)` in some cases), which is very slow.
> Avoid extra work in the good case in `try_catch()`

- R/compat-obj-type.R
- R/compat-types-check.R
- R/fn.R
- R/lifecycle-deprecated.R
- R/utils.R
- src/internal/cnd.c
- tests/testthat/_snaps/arg.md
- tests/testthat/_snaps/cnd-signal.md
- tests/testthat/_snaps/cnd.md
- tests/testthat/_snaps/compat-types-check.md
- tests/testthat/_snaps/eval-tidy.md
- tests/testthat/_snaps/fn.md
- tests/testthat/_snaps/friendly-type.md
- tests/testthat/_snaps/s3.md
- tests/testthat/_snaps/session.md
- tests/testthat/_snaps/trace.md
- tests/testthat/helper-rlang.R
- tests/testthat/test-compat-types-check.R
- tests/testthat/test-friendly-type.R
- tests/testthat/test-s3.R
- tests/testthat/test-vec-new.R
- Add `min` and `max` to `check_number_whole()` and its decimal variant.
- Refactor `obj_type_friendly()` to more consistently show values. This is the largest part of this PR, with many new tests, and some functionality extracted in a separate `vec_type_friendly()` helper.
The goal of the second change is to consistently show values in error messages when a range is requested, so that we don't get messages like "must be a number greater than 0, not a number".
```r
foo <- function(x, min = -Inf, max = Inf) {
check_number_whole(x, min = min, max = max)
x
}
foo(1, max = 0)
#> Error in `foo()`:
#> ! `x` must be a number smaller than 0, not 1.
foo(-1, min = 0)
#> Error in `foo()`:
#> ! `x` must be a number larger than 0, not -1.
foo(10, min = 1, max = 5)
#> Error in `foo()`:
#> ! `x` must be …
```
> Add `min` and `max` to number checkers

- src/internal/cnd.c
In `src/internal/init.c`, the function `ffi_new_condition` is set in the `r_callables` table to take 3 arguments, but the implementation takes 4 arguments. This breaks rlang when running under WebAssembly, where function pointer signatures must be consistent.
It doesn't look like the `error_call` argument is used, so I've removed it to leave the first 3 arguments.
> Remove unused extra argument in `ffi_new_condition`

- NEWS.md
- src/rlang/dyn-array.c
- src/rlang/dyn-array.h
The push-back operation of our dynamic vector is probably one of the most commonly used ops in practice, so it would be nice if this was really fast. Currently it calls into `r_dyn_push_back()`, which is generic (which is great!) but slow because of its generality. 
I was looking into replacing our vctrs `growable` type with dynamic vectors and was surprised to see just how slow our dynamic push-back was in comparison.
Consider this simple example of doing repeated push-backs and no resizing.
```r
r_obj* ffi_test_push_back() {
r_ssize size = 100000;
struct r_dyn_array* p_vec = r_new_dyn_vector(R_TYPE_integer, size);
KEEP(p_vec->shelter);
for (r_ssize i = 0; i < size; ++i) {
r_dyn_int_push_back(p_vec, i);
}
r_obj* out = r_dyn_unwrap(p_vec);
FREE(1);
return out;
}
```
```r …
```
> Optimize `r_dyn_*_push_back()` for vector types

- NEWS.md
- src/internal/eval-tidy.c
- src/rlang/decl/env-decl.h
- src/rlang/env.c
This PR was motivated by this dplyr issue https://github.com/tidyverse/dplyr/issues/6666
If we are going to create a fresh data mask at each group evaluation, then mask creation needs to be very fast.
This PR helps in two ways:
- Reduce the initial data mask size from 100 down to 10. I don't think that we really need such a large initial mask size, since most of the time we don't use `<-` in `eval_tidy()` calls to poke into the mask. I think most of the time the expressions we pass to `eval_tidy()` are function calls like `eval_tidy(mean(x), mask)` or something similar, so I don't think the mask env needs to be this big.
- Optimize `r_alloc_environment()` to use `R_NewEnv()` on R >=4.1.0, which is a C level version of `new.env()`.
``` r
library(rlang)
env <- new_environment() …
```
> Optimize `new_data_mask()` and `r_alloc_environment()`

- src/internal/eval-tidy.c
- src/rlang/env.h
For use in `rlang_new_ctxt_pronoun()` where we don't poke into the `pronoun` environment at all, which makes it slightly faster and allocate less memory. `new_data_mask()` now shows up as allocating 0 memory by profmem.
- This is actually how we define `r_new_environment()` in vctrs, so we could switch that out for this https://github.com/r-lib/vctrs/blob/793d028250824ce907970135105c461c66b7dd25/src/utils.h#L260
- I was tempted to make this what happens if you supply `0` in `r_alloc_environment()`, but that felt wrong because it creates a non-hashed environment and is different from what `R_NewEnv()` does (by using the "default" size of 29)
> New `r_alloc_empty_environment()`

- NEWS.md
- src/rlang/c-utils.h
- tests/testthat/test-types.R
Hello wonderful people :)
Currently rlang has chosen 2^52 as the upper bound for integerish doubles.
However the effective lower bound is somewhere around -2^63-2^10 which is much lower than -2^52 which was likely the intended bound. This PR adds the  lower bound `RLANG_MIN_DOUBLE_INT = -2^52` and append some test statements. If not adopting fix `rlang::is_integerish(-2^63)`will return `TRUE` although -2^63 is not unambiguously represented as a binary64 floating point.
I don't understand why the bound should not to allow representation of all the integers {-2^53+1, ...,  -1, 0, 1, ..., 2^53-1} . The double has 53 significant bits and the sign bit. [Wikipedia says](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#Precision_limitations_on_integer_values) -2^53 to 2^53 …
> fix `is_integerish()` lower bound for large negative doubles

- R/cnd-abort.R
- tests/testthat/_snaps/c-api.md
- tests/testthat/_snaps/cnd-abort.md
Flagged by our typo tool in vctrs:
https://github.com/r-lib/vctrs/blob/af3fcc486664e30b588df1296a212e583ef00d18/tests/testthat/_snaps/expand.md?plain=1#L61
> Fix typo (duplicate https://)

- NEWS.md
- R/nse-inject.R
- man/englue.Rd
- tests/testthat/_snaps/nse-inject.md
- tests/testthat/test-nse-inject.R
> Support wrapping `englue()`

- NEWS.md
- src/rlang/vec-lgl.c
- tests/testthat/test-c-api.R
Closes https://github.com/r-lib/rlang/pull/1487
This is an alternative approach for optimizing `r_lgl_sum()` and `r_lgl_which()` to what is done in #1487.
The way I optimize here is by avoiding branching, like what I did in `vec_pany()` and `vec_pall()`. I think I like this better than having magic numbers like in #1487.
The main reason I like this approach is that it isn't "jumpy", so the compiler can't get screwed by inaccurate branch predictions. This mainly shows up in the timings in the 50/50 splits between TRUE/FALSE, where this is drastically faster most of the time.
The downside of this approach is that because it doesn't rely on branch prediction as much, cases like 1% `TRUE` can be a little slower, but not much, and I think the tradeoff of losing a little performance here vs the …
> Optimize `r_lgl_sum()` and `r_lgl_which()`

- NEWS.md
- R/cnd-abort.R
- R/cnd-handlers.R
- R/cnd-signal.R
- R/cnd.R
- man/abort.Rd
- man/cnd_inherits.Rd
- man/try_fetch.Rd
- src/internal/cnd-handlers.c
- tests/testthat/test-cnd-entrace.R
- tests/testthat/test-cnd-handlers.R
- tests/testthat/test-cnd-signal.R
- tests/testthat/test-cnd.R
Follow up to #1573 (see discussion there).
New `.inherit = <bool>` argument. This controls whether `cnd_inherits()` and `try_fetch()` are allowed to match parent conditions. The default is `TRUE` in `abort()`. In `warn()` and `inform()`, the default is `TRUE` in the general case, and `FALSE` when `parent` is a condition of higher severity. This prevents matching downgraded conditions unexpectedly.
The parameter is stored in `cnd$rlang$inherit`. This is a public field (otherwise it'd be stored in `rlang$internal$`. It's namespaced to avoid name clashes with subclasses.
cc @DavisVaughan @gaborcsardi
> Turning off condition inheritance

- R/lifecycle-deprecated.R
- man/vector-coercion.Rd
Because they are no longer _soft_ deprecated
> Bump coercion helper deprecation badge status

- R/standalone-types-check.R
- tests/testthat/_snaps/standalone-types-check.md
- tests/testthat/test-standalone-types-check.R
I stumbled this when working on #1590. As they don't accept `NA` it makes sense to explicitly pass `allow_na = FALSE` so that you cannot pass it accidentally via the `...` arguments (this happened in the tests).
I thought this isn't worth a NEWS entry but if you want I can add one.
> Pass `allow_na = FALSE`

- R/standalone-types-check.R
- tests/testthat/_snaps/standalone-types-check.md
This PR aims to fix #1591.
Briefly, it does two things:
* Messages are about 'a whole number' if `allow_decimal = FALSE`, even when the number is OOB.
* The OOB check uses closed intervals, so for the upper and lower violation (not both), it now signals 'or equal to' as well.
If you'd like me to make an entry in the changelog or NEWS.md as well, please let me know.
> `check_number_*()` error messages

- R/c-lib.R
`proj_path()` currently has a bug in dev usethis where calling it without any arguments returns `character()` rather than the project path, but I've also been told that `proj_get()` is a better way to do this anyways.
(I won't merge this until after rlang is accepted and you can bump the version)
> Switch from `proj_path()` to `proj_get()`

- NEWS.md
- R/parse.R
- man/parse_expr.Rd
Closes #1603 
It turns out that in both rlang 1.0.6 and 1.1.0, source information was already being dropped in all cases (I wanted to ensure that removing usage of `flatten()` was not the result of this change, and it doesn't seem to be).
I think this makes sense as the source reference information is typically attached to the expression object, and:
- `parse_expr()` returns the individual expression element, not the expression vector
- `parse_exprs()` can parse and flatten _multiple_ expressions, and since each expression can return >1 element from `parse()`, you don't have a good 1:1 mapping between the source information and the flattened parsed expressions, so it makes sense to just drop the source information here too
> Never keep sources in `parse_*()`

- tests/testthat/test-dots-ellipsis.R
Which now correctly checks the overall class of the underlying condition when you set `class`
(And can we plan a patch release in the next two weeks?)
> Fix for dev testthat

- NEWS.md
- R/standalone-obj-type.R
- tests/testthat/_snaps/cnd-signal.md
- tests/testthat/test-friendly-type.R
Motivated by the fact that subclassing things like rcrds can result in very distracting class lists, with no added benefit
```r
> zoned_time_zone(duration_days(1))
Error in `zoned_time_zone()`:
! `x` must be a <clock_zoned_time>, not a <clock_duration/clock_rcrd/vctrs_rcrd/vctrs_vctr> object.
```
> Only report the first class in `obj_type_friendly()`

- NEWS.md
- R/cnd-abort.R
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/fixtures/error-show-messages.R
- tests/testthat/test-cnd-abort.R
Closes #1630 
Test generation is a little tricky, but I followed some other existing examples
> Respect `show.error.messages` in `abort()`

- NEWS.md
- R/trace.R
- tests/testthat/_snaps/cnd-message.md
- tests/testthat/_snaps/trace.md
Seems like it was introduced here, but I could not discern a reason why
https://github.com/r-lib/rlang/pull/511/files#diff-b0faac068b86ed24d71c6942ed58a7e28675e4acb353e36b4b7d323c5862bb54R179
https://github.com/r-lib/rlang/assets/19150088/f2e94ab3-8d47-4bf9-9e5a-590a3de0c981
> Fix off by one typo in source column location

- NEWS.md
- R/expr.R
- tests/testthat/test-expr.R
Closes https://github.com/r-lib/rlang/issues/1655
Copy of issue below:
One of the main "significant user-visible changes" for the upcoming R release, v4.4, is that:
- `is.atomic(NULL)` now returns `FALSE`, as `NULL` is not an atomic vector. Strict back compatibility would replace `is.atomic(foo)` by `(is.null(foo) || is.atomic(foo))` but should happen sparingly only.
`expr_label(NULL)` under R <4.4 would return "NULL"
`expr_label(NULL)` under R  4.4 would return "\`NULL\`"
Although `expr_label()` is already under lifecycle label questioning, this may have _minor_ unintended consequences
```
expr_label <- function(expr) {
if (is.character(expr)) {
encodeString(expr, quote = '"')
} else if (is.atomic(expr)) { # should this be replaced with (is.null(expr) || is.atomic(expr))  ?
format(expr) …
```
> Closes #1655 add back-compatibility to `expr_label()` for incoming `is.atomic(NULL)` change in R version 4.4

- NEWS.md
- R/standalone-cli.R
I recently came across a slowdown when profiling some tidymodels code that I thought might be worth raising. The `utils::packageVersion("rlang") >= "0.4.2"` check in `standalone-cli.R` adds up for us downstream.
With rlang 1.1.1:
``` r
bench::mark(
signal = rlang::signal(class = "boop"),
group_by = dplyr::group_by(mtcars, cyl),
check = FALSE
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 signal        276µs    288µs     3393.  296.68KB     16.8
#> 2 group_by      860µs    900µs     1080.    3.49MB     16.8
```
With this PR:
``` r
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 …
```
> speed up package version check in `.rlang_cli_compat()`

- NEWS.md
- R/utils.R
Introduced in https://github.com/rstudio/rstudio/pull/12096
I think this has been out long enough that it would be ok to move to it unconditionally? I'm not sure if a release version of RStudio without `x-r-run` support was ever released, if so it would have been released between June->Oct of 2022 (based on looking at commit history), so that's a 4 month window where an RStudio release may have come out without support for `x-r-run`.
In the worst case where it isn't supported, it just means the `last_trace()` hyperlinks won't work until they upgrade RStudio I guess (that seems to be all it is used for)
> Use modern `x-r-run` convention

- R/aaa.R
- man/on_load.Rd
> docs: Document `on_load()` detail

- R/aaa.R
- man/on_load.Rd
This gives better tracebacks, I suppose.
> docs: Wrap `on_load()` contents in examples with braces

- R/standalone-vctrs.R
- tests/testthat/test-standalone-vctrs.R
This PR aims to fix #1700.
It restores an error that should be thrown when `size = 1` is requested, but input has larger vectors.
Reprex from issue with this PR:
``` r
rlang:::vec_recycle_common(list(a = 1, b = 1:2), size = 1)
#> Error: Inputs can't be recycled to `size`.
```
<sup>Created on 2024-04-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
> Fix bug in `vec_recycle_common()`

- R/standalone-s3-register.R
From https://github.com/r-lib/vctrs/pull/1901
> Mention `usethis::use_standalone()` and fix package name typo

- R/cnd-abort.R
- man/abort.Rd
I discovered yesterday that if you wanted  to hard-code the `call` argument, it was possible, but never found this in rlang's `abort()` documentation,
I thought adding an example could be useful? Sometimes, I think it can be useful to hard-code it? May be easier to learn to use this than all of rlang's infrastructure.
> Show how to use call = `base::call()` in `abort()`

- R/dots-ellipsis.R
- man/check_dots_empty.Rd
- man/check_dots_unnamed.Rd
- man/check_dots_used.Rd
Currently, there is no reference to other dot checking functions. So adding a `@family` adds the following to see also
Maybe worth adding `dots_n()`?
> Add cross-ref between the ellipsis checking functions

- src/rlang/vec.h
This is to fix one of many CRAN Notes related to newly-added "non-API"s.
```
Version: 1.1.4
Check: compiled code
Result: NOTE
File ‘rlang/libs/rlang.so’:
Found non-API calls to R: ‘ENVFLAGS’, ‘FRAME’, ‘HASHTAB’, ‘LEVELS’,
‘NAMED’, ‘PRENV’, ‘PRVALUE’, ‘RDEBUG’, ‘R_PromiseExpr’,
‘Rf_findVarInFrame3’, ‘SETLENGTH’, ‘SET_BODY’, ‘SET_CLOENV’,
‘SET_ENCLOS’, ‘SET_ENVFLAGS’, ‘SET_FORMALS’, ‘SET_GROWABLE_BIT’,
‘SET_RDEBUG’, ‘SET_TRUELENGTH’, ‘SET_TYPEOF’, ‘STRING_PTR’,
‘XTRUELENGTH’
Compiled code should not call non-API entry points in R.
```
(https://cran.r-project.org/web/checks/check_results_rlang.html)
> Replace STRING_PTR with STRING_PTR_RO

- DESCRIPTION
- NEWS.md
- R/env.R
- R/rlang-package.R
- man/env_unlock.Rd
- src/internal/env.c
- src/internal/init.c
- tests/testthat/test-env.R
Closes https://github.com/r-lib/rlang/issues/1705
`env_unlock()` is now defunct. Downstream deps have been warned of this 2 months ago.
The main revdep is `pkgload::load_all()` which is updated in https://github.com/r-lib/pkgload/pull/286 and will soon be sent to CRAN. It's likely people will end up with mismatched versions so `env_unlock()` detects outdated pkgload version and recommends to update.
> Deprecate `env_unlock()`

- NEWS.md
- R/attr.R
- tests/testthat/test-attr.R
> dictionaryish(NULL) return true

- R/standalone-lifecycle.R
This wasn't documented in the file's requirements so raised an R CMD check warning when I tried using the file in another project.
Thanks!
> fix: remove call to `glue::glue()` in `standalone-lifecycle.R`

- R/call.R
Some examples in call_modify() predate the introduction of zap() and use the older `[arg] = NULL` syntax.  In particular, this made line 560's example, `call_modify(call, bar = NULL, bar = missing_arg())`, no longer illustrate its key behavior.  Changed that, plus 2 other (likely less important) examples where argument removal seems to have been intended.
> fixing some call_modify examples w/ NULL -> zap()

- R/standalone-purrr.R
``` r
compact1 <- function(x) Filter(length, x)
compact2 <- function(x) x[as.logical(lengths(x))]
compact3 <- function(x) x[lengths(x) > 0L]
x <- list(1:100, NULL, NULL, NULL, 1:100)
bench::mark(
compact1(x),
compact2(x),
compact3(x),
iterations = 100
)
#> # A tibble: 3 × 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 compact1(x)   2.91µs   3.28µs    13534.        0B        0
#> 2 compact2(x) 491.97ns 574.04ns   115615.        0B        0
#> 3 compact3(x) 492.03ns 574.04ns   138659.        0B        0
```
<sup>Created on 2025-01-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> perf: faster standalone compact

- R/session.R
Can safely shortcut when package versions are not specified.
This prevents the full code path being run every time the function is called within a session, and is equivalent to the user memoizing the result.
Takes 3 microseconds, which is not much to give back on the initial run when we've saved some hundreds of microseconds in #1777.
``` r
library(rlang)
bench::mark(check_installed("later"))
#> # A tibble: 1 × 6
#>   expression                        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 "check_installed(\"later\")"   2.47µs   3.01µs   305568.    5.61MB     30.6
```
<sup>Created on 2025-02-20 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
This should be applied with #1777 but is …
> Speed up `check_installed()` - shortcut when package is already loaded

- R/session.R
As suggested by @hadley in https://github.com/r-lib/rlang/issues/1776#issuecomment-2654610545. This PR leaves that issue open for further improvements.
Additionally closes https://github.com/r-lib/rlang/issues/1608 by replacing the slow call to `system.file()`.
> Speed up `check_installed()` - faster check for whether a package is on disk

- NEWS.md
the following was left as is
unconditionally would be more common in modern English
in `#393` had been used the wording non-existing args rather than unexisting arguments
```
$ grep -nr inconditionally rlang
rlang/NEWS.md:2201:Deprecated functions and arguments issue a warning inconditionally,
$ grep -nr unexisting rlang
rlang/NEWS.md:2052:* `call_modify()` now supports removing unexisting arguments (#393)
rlang/tests/testthat/test-call.R:209:test_that("can remove unexisting arguments (#393)", {
$
> news typos

- R/types.R
- tests/testthat/test-call.R
- tests/testthat/test-deparse.R
- tests/testthat/test-types.R
- `{}` are no longer expanded
- `types.R` can now actually be formatted since `NULL =` is now allowed in call argument position
> Format with Air 0.7.0

- NEWS.md
- R/expr.R
- tests/testthat/test-expr.R
Add an `attributes()` check to `is_syntactic_literal()` to ensure that syntactic-literal-like objects such as factors and arrays are not treated as syntactic literals.
Fixes #1817.
> Make `is_syntactic_literal()` more strict

- src/rlang/node.c
- src/rlang/node.h
`r_pairlist_find()` was showing up in my Instruments profiles as not being inlined. It is used in some of the deepest layers of vctrs via `r_dim()` and `r_class()` through the following:
- `r_dim()`
- calls `r_attrib_get()`
- calls `r_pairlist_get()`
- calls `r_pairlist_find()`
`r_dim()` itself is used on every iteration of `vec_size_common()` when computing the `vec_size()` of an object.
It's definitely a simple enough loop that we can inline it, and after inlining it does disappear from the Instruments profile
> Inline `r_pairlist_find()`

- R/standalone-obj-type.R
- tests/testthat/_snaps/standalone-obj-type.md
- tests/testthat/test-friendly-type.R
- tests/testthat/test-standalone-obj-type.R
In vctrs, we are trying to be fairly strict about the type of `condition` in `vec_if_else()`. In particular, we disallow arrays from being passed as `condition`, even 1D arrays (we do this consistently across `vec_if_else()`, `list_combine()`, vec_case_when()`, and `vec_replace_when()`, all of which can take logical "condition" indices).
https://github.com/r-lib/vctrs/blob/f27ab24c7eb0b1d78d48bd1d39175a1ecf7d4411/src/slice-assign.c#L964-L971
Unfortunately, `obj_type_friendly()` currently reports 1D arrays as identical to vectors resulting in the following not-useful error message
```r
Error in `if_else()`:
! `condition` must be a logical vector, not a logical vector.
```
I'd argue that 1D arrays should be reported _as arrays_ by `obj_type_friendly()`. In other words, we'd have:
- `n_dim = …
> Report array dimensionality in `obj_type_friendly()`
