- DESCRIPTION
- R/compat-lazyeval.R
- tests/testthat/test-compat.R
Includes #88 
This should complete the set of lazy compat methods.
> Fix lazy compat

- R/quo.R
- man/quosure.Rd
> Fix documentation typo

- R/env.R
- R/utils.R
- tests/testthat/test-env.R
- tests/testthat/test-tidy-eval.R
> Fix environment supplied as data to eval_tidy()

- NEWS.md
- R/dots.R
- R/env.R
- man/dots_list.Rd
- man/env.Rd
- tests/testthat/test-env.R
- vignettes/releases/rlang-0.1.Rmd
And rename `parent` argument to `.parent` in `child_env()`.
> Fix partial matching in env_bind()

- R/compat-lazyeval.R
- R/compat-oldrel.R
- R/compat-purrr.R
`nocov` ignores just the line it is on, you need to use `nocov start` to
define a block to ignore
> Fix coverage comments

- NEWS.md
- R/operators.R
- src/init.c
- src/replace-na.c
> Fix symbol collision with tidyr::replace_na()

- R/eval-tidy.R
- man/as_overscope.Rd
- man/eval_tidy_.Rd
Otherwise, the significance of `top = NULL` is unclear from the docs alone.
> Explain the default value of top

- tests/testthat/test-stack.R
> Fix partial matching error

- NEWS.md
- R/expr-interp.R
- R/formula.R
- R/operators.R
- R/quo.R
- man/as_quosure.Rd
- man/is_formula.Rd
- man/op-definition.Rd
- man/quasiquotation.Rd
- tests/testthat/test-formula.R
- tests/testthat/test-tidy-unquote.R
- tests/testthat/test-types.R
> Issue an error when `:=` is called directly

- R/eval.R
- R/lifecycle.R
- man/eval_bare.Rd
- man/invoke.Rd
- man/lifecycle.Rd
- man/with_env.Rd
And mark `with_env()`, `locally()` and `invoke()` as experimental.
> Update eval_bare() documentation

- NEWS.md
- R/call.R
- man/call_modify.Rd
- man/call_standardise.Rd
> Changes for redpen

- R/eval-tidy.R
- man/as_data_mask.Rd
- man/as_overscope.Rd
- man/eval_tidy.Rd
- man/eval_tidy_.Rd
- man/tidyeval-data.Rd
> Update tidy eval low level documentation

- R/vec-new.R
- man/vector-construction.Rd
> Remove self-reference

- R/lifecycle-retired.R
> pass caller_env() of lang_standardise() to call_standardise()

- DESCRIPTION
Replace *tidyverse* with *r-lib*
> Update repository ownership

- src/lib/parse.h
> Fix LD warning

- R/quasiquotation.R
- man/quasiquotation.Rd
- man/stack.Rd
Note: man/stack.Rd changed but I didn't change it or R/stack.R :(
> Spelling correction

- src/lib/vec-chr.h
- tests/testthat/test-eval-tidy.R
Closes #538
Closes tidyverse/ggplot2#2665
cc @krlmlr
> Translate names to native encoding before creating data mask

- R/eval-tidy.R
- man/as_data_mask.Rd
> Fix typo in eval_tidy() doc

- NEWS.md
- src/internal/env-binding.c
- tests/testthat/test-env-binding.R
> Evaluate promises & active bindings in env_get()

- R/eval-tidy.R
- man/as_data_mask.Rd
I was attempting to use new_data_mask and found it difficult to figure out exactly what it was doing from the docs. I added an example that walks through creating a multi-environment data mask with pronouns from scratch.
> Edit examples in new_data_mask

- NEWS.md
- R/env-binding.R
- R/fn.R
- man/env_bind.Rd
- tests/testthat/test-env-binding.R
- tests/testthat/test-fn.R
> Handle quosures in env_bind_promise() and env_bind_active()

- NEWS.md
- R/types.R
- man/is_integerish.Rd
- src/lib/vec.c
- tests/testthat/test-types.R
> Support large double values in is_integerish()

- R/cnd.R
- R/env.R
- R/quo.R
- R/utils.R
- tests/testthat/test-cnd-error-parent-default.txt
- tests/testthat/test-cnd-error-parent.txt
- tests/testthat/test-cnd-error-print-no-message.txt
- tests/testthat/test-cnd-error-str.txt
- tests/testthat/test-env.R
Closes #452
Code for testing locally:
```r
quo(foo)
local(quo(foo))
env_print()
f <- function() tryCatch(g())
h <- function() abort("The error message")
catch_cnd(f())
summary(catch_cnd(f()))
```
> Standardise print methods

- R/eval-tidy.R
- man/eval_tidy.Rd
- man/eval_tidy_.Rd
- What happens to `data`
- When to use `eval_tidy()`
> Improve documentation of eval_tidy()

- NEWS.md
- R/fn.R
- tests/testthat/test-fn.R
closes https://github.com/r-lib/rlang/issues/735
> as_function() return value inherits from function

- R/compat-purrr.R
to `compat-purrr.R`.
https://github.com/r-lib/vctrs/pull/207#issuecomment-470281943
> Add walk()

- NEWS.md
- R/state.R
- man/is_interactive.Rd
- tests/testthat/test-state.R
> Teach is_interactive() about TESTTHAT="true"

- NEWS.md
- R/env-special.R
- man/ns_env.Rd
- tests/testthat/test-env-special.R
And remove support for default argument.
> Support functions and environments in `ns_env()` and `ns_env_name()`

- NEWS.md
- R/env-binding.R
> Use `value` not `data[[nm]]` in default binder

- R/fn.R
- man/as_function.Rd
> Document caveat when using quasiquotation with as_function()

- NEWS.md
- R/cnd-entrace.R
- R/cnd-signal.R
- man/abort.Rd
- tests/sink.R
> Print messages to `stdout` by default

- NEWS.md
- R/cnd-abort.R
- tests/testthat/test-cnd-error-conditionMessage.txt
- tests/testthat/test-cnd-error-parent.txt
- tests/testthat/test-cnd-error.txt
Suggested in https://twitter.com/markhw_/status/1194263749198303233
> Fix `last_error()` reminder

- R/cnd-handlers.R
- man/catch_cnd.Rd
> Use signal() instead of cnd_signal()

- NEWS.md
- R/deparse.R
- tests/testthat/test-deparse.R
> Fix deparse issues

- R/cnd-signal.R
- tests/testthat/test-cnd-signal.R
> Return invisibly from inform()

- R/nse-force.R
Fixes minor typo in nse-force docs
> Fix typo in nse-force / walrus operator docs

- R/arg.R
- tests/testthat/test-arg.R
- tests/testthat/test-typo-suggest.txt
#914 introduced a check which appears to be too strict - on debug I see that the ordering of the values can be changed. This PR appears to resolve a lot of issues (related: https://github.com/r-lib/vctrs/issues/790) I've been seeing.
Fixes https://github.com/r-lib/vctrs/issues/790
> Repair arg_match failure

- R/state.R
- man/is_interactive.Rd
This is just a suggestion since it wasn't immediately clear to me what would happen in this case. I had to test it to understand.
> Be more explicit about what happens if knitr, an RStudio notebook or testthat is in progress

- R/fn.R
- man/is_function.Rd
See https://rlang.r-lib.org/reference/is_function.html
> Enable linking of wikipedia page

- NEWS.md
- R/env-special.R
- man/is_installed.Rd
- tests/testthat/test-env-special.R
I'd like to have a vectorized `is_installed()` so I just went ahead and created this PR.
> Vectorize `is_installed()`

- R/cnd-abort.R
- R/cnd-signal.R
- R/env.R
- R/eval-tidy.R
- R/lifecycle-retired.R
- R/lifecycle.R
- R/types.R
- man/abort.Rd
- man/as_data_mask.Rd
- man/bare-type-predicates.Rd
- man/env_parent.Rd
- man/lifecycle.Rd
- man/scalar-type-predicates.Rd
- man/type-predicates.Rd
- tests/testthat/test-cnd-signal.R
- tests/testthat/test-eval-tidy.R
- tests/testthat/test-retired.R
- tests/testthat/test-vec-new.R
> Clean up defunct arguments and lifecycle documentation

- NEWS.md
- R/parse.R
- R/utils.R
- man/parse_expr.Rd
- tests/testthat/test-parse.R
> Preserve names in `parse_exprs()`

- R/utils.R
Should be a bit faster for long strings, not measured.
> Avoid double paste() in paste_line()

- R/cnd-signal.R
- man/abort.Rd
- tests/sink.R
- tests/testthat/test-cnd-signal.R
> Send messages to `stderr` when a sink is active

- NEWS.md
- src/internal/expr-interp-rotate.c
- tests/testthat/test-nse-force.R
> Fix mutation of injected objects

- .github/workflows/R-CMD-check.yaml
- R/c-lib.R
- src/Makevars
- src/internal/eval-tidy.c
- src/rlang-rcc.cpp
- src/rlang/c-utils.h
- src/rlang/cpp/rlang.cpp
- src/rlang/cpp/vec.cpp
- src/rlang/dyn-list-of.h
- src/rlang/env.h
- src/rlang/rlang.hpp
- src/rlang/sexp.h
- src/rlang/vec.h
Only `r_int_unique()` for now, we'll flesh it out over time.
> Draft wrapping of STL algorithms in the rlang C library

- NEWS.md
- R/formula.R
- man/is_formula.Rd
- tests/testthat/test-formula.R
> Fix `scoped` handling in `is_bare_formula()`

- NEWS.md
- R/arg.R
- tests/testthat/_snaps/arg.md
- tests/testthat/test-arg.R
> Mention supplied argument in `arg_match()`

- R/arg.R
- tests/testthat/_snaps/arg.md
- tests/testthat/test-arg.R
This closes #1152. I added case-insensitive match only after a failed case-sensitive one as this seems to suggest better candidates overall.
> Update `arg_match()` to do case-insensitive match.

- DESCRIPTION
- src/version.c
In reference to function name change: 
https://github.com/r-lib/rlang/commit/33f12f3b97af38a9b26ef76e46228b58ff15ebb4
> Bump dev version

- NEWS.md
- R/env-special.R
- man/is_installed.Rd
- tests/testthat/_snaps/env-special.md
- tests/testthat/test-env-special.R
> Add `version` argument to `is_installed()` and `check_installed()`

- R/quo.R
so that pillar can add an ellipsis to the generic.
> Add ellipsis to type_sum() method

- src/rlang/attrib.h
- src/rlang/globals.c
- src/rlang/globals.h
> Add dim/dim_names utilities

- NEWS.md
- R/dots.R
- man/list2.Rd
- man/nse-defuse.Rd
- src/internal/decl/dots-decl.h
- src/internal/dots.c
- tests/testthat/test-dots.R
- tests/testthat/test-nse-defuse.R
> Allow default names with `.named = NULL`

- NEWS.md
- R/env.R
- man/env_clone.Rd
- src/rlang/decl/env-decl.h
- src/rlang/env.c
- src/rlang/env.h
- tests/testthat/test-env.R
Closes #1228
Part of r-lib/testthat#1405
> Bind promises and active bindings when cloning environment

- src/internal/arg.c
- src/internal/decl/sym-unescape-decl.h
- src/internal/dots.c
- src/internal/init.c
- src/internal/nse-inject.c
- src/internal/sym-unescape.c
- src/rlang/env.c
- src/rlang/rlang.c
- src/rlang/sym.c
- src/rlang/sym.h
- tests/testthat/helper-rlang.R
- tests/testthat/test-encoding.R
> Fix native to UTF-8 conversion in dots collectors

- NEWS.md
- R/arg.R
- man/arg_match.Rd
- tests/testthat/_snaps/arg.md
- tests/testthat/test-arg.R
> Add `multiple` argument to `arg_match()`

- R/deparse.R
- R/utils.R
- tests/testthat/test-deparse.R
> Less aggressive ellipsizing in as_label

- NEWS.md
- R/cnd.R
- man/topic-error-call.Rd
- man/topic-error-chaining.Rd
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-entrace.md
- tests/testthat/_snaps/cnd-handlers.md
- tests/testthat/_snaps/cnd-signal.md
- tests/testthat/_snaps/cnd.md
- tests/testthat/_snaps/current/cnd-abort.md
- tests/testthat/_snaps/pre-3.6.0/cnd-abort.md
- tests/testthat/_snaps/trace.md
> Add `---` ruler between error messages and backtraces

- NEWS.md
- R/cnd-abort.R
- R/cnd.R
- R/compat-cli.R
- R/trace.R
- R/utils.R
- tests/testthat/helper-cli.R
- tests/testthat/test-compat-cli.R
- tests/testthat/test-trace.R
> Add hyperlinks to src_loc()

- R/cnd-abort.R
- R/cnd-last.R
- R/cnd.R
- R/trace.R
- R/utils-cli-tree.R
- R/utils.R
- man/last_error.Rd
- tests/testthat/_snaps/cnd.md
- tests/testthat/_snaps/trace.md
- tests/testthat/helper-trace.R
- tests/testthat/test-trace.R
Enable with:
```r
options(
"rlang:::trace_display_tree" = TRUE
)
```
> Draft tree display mode

- R/compat-cli.R
- R/compat-downstream-deps.R
- R/compat-purrr.R
- R/compat-rlang.R
- R/compat-s3-register.R
- R/compat-vctrs.R
> Refer to main branch in compat files

- NEWS.md
- R/deparse.R
- tests/testthat/_snaps/trace.md
- tests/testthat/test-deparse.R
- tests/testthat/test-trace.R
> Fix backtrace generation with long lists of arguments

- src/rlang/vec.h
As noted in https://github.com/r-lib/vctrs/pull/1616#discussion_r944609452
> Tweak `r_arg_as_*()` error messages

- R/trace.R
- rlang.Rproj
related to https://github.com/rstudio/rstudio/issues/11697#issuecomment-1208093564
> normalizePath(<srcfile$filename>)

- R/cnd-handlers.R
- man/try_fetch.Rd
> Minor documentation fixes

- R/cnd-handlers.R
- man/rmd/topic-error-chaining.Rmd
- man/topic-error-chaining.Rd
- man/try_fetch.Rd
Removing "currently unreleased" comments.
> R 4.2 now released

- NEWS.md
- R/compat-cli.R
- R/compat-downstream-deps.R
- R/compat-obj-type.R
- R/compat-rlang.R
- R/compat-s3-register.R
- R/compat-types-check.R
> Fix onload check

- R/compat-types-check.R
- tests/testthat/_snaps/compat-types-check.md
- tests/testthat/test-compat-types-check.R
Branched from #1493.
Part of #1481.
> Improve absent argument errors in input checkers

- NEWS.md
- R/standalone-types-check.R
- tests/testthat/_snaps/compat-types-check.md
- tests/testthat/test-compat-types-check.R
For `if_else()` and `case_when()` to validate the condition inputs
> Add `check_logical()`

- NEWS.md
- R/attr.R
- src/internal/attr.c
- src/internal/decl/attr-decl.h
- src/internal/init.c
- src/rlang/globals.c
- src/rlang/globals.h
- src/rlang/node.c
- tests/testthat/test-attr.R
Closes #1513.
@wch could you try this branch out and see if it fixes your performance issues please?
> Rewrite `zap_srcref()` in C

- NEWS.md
- R/nse-defuse.R
- man/defusing-advanced.Rd
- man/enquo.Rd
- tests/testthat/test-nse-defuse.R
> Add `.ignore_null` argument for `enquos()` and friends

- NEWS.md
- src/internal/dots.c
- src/rlang/node.c
- tests/testthat/_snaps/dots.md
- tests/testthat/test-dots.R
> Clone only the node tree before injection

- NEWS.md
- R/cnd-signal.R
- R/lifecycle-deprecated.R
- R/quo.R
- R/standalone-lifecycle.R
- R/trace.R
- src/internal/dots.c
- src/internal/eval-tidy.c
- src/internal/nse-inject.c
- src/internal/utils.c
- src/internal/utils.h
- tests/testthat/_snaps/cnd-abort.md
- tests/testthat/_snaps/cnd-signal.md
- tests/testthat/_snaps/lifecycle.md
- tests/testthat/test-c-api.R
- tests/testthat/test-deprecated.R
- tests/testthat/test-eval-tidy.R
- tests/testthat/test-lifecycle.R
- tests/testthat/test-nse-defuse.R
- tests/testthat/test-nse-inject.R
- tests/testthat/test-quo.R
- tests/testthat/test-vec.R
Branched from #1574.
This updates the lifecycle API and internals to match the current lifecycle package.
FYI @hadley
> Standalone lifecycle update

- NEWS.md
- R/standalone-types-check.R
- tests/testthat/_snaps/standalone-types-check.md
- tests/testthat/test-standalone-types-check.R
> Add `check_data_frame()`

- NEWS.md
- R/standalone-types-check.R
- tests/testthat/test-standalone-types-check.R
> Add `allow_infinite` to `check_number_whole()`

- src/rlang/attrib.c
> Protect attribute pairlist in `r_clone2()`

- R/call.R
> Fix doc typo
